"""
Bot Generator for the Buddy Core System.

Provides Bot-on-Demand: parse intent → inject tools → generate template code
→ build → deploy.  All operations are in-memory; no real deployments occur.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from bots.buddy_core.intent_parser import IntentParser, Industry
from bots.buddy_core.tool_db import ToolDB


class BotGeneratorError(Exception):
    """Raised when bot generation fails."""


class BotStatus(Enum):
    PENDING = "pending"
    BUILDING = "building"
    READY = "ready"
    DEPLOYED = "deployed"
    FAILED = "failed"


@dataclass
class BotDNA:
    """Blueprint metadata for a generated bot."""

    name: str
    purpose: str
    industry: str
    revenue_model: list
    apis: list
    automation_level: str
    target_user: str
    created_at: datetime = field(default_factory=datetime.utcnow)
    metadata: dict = field(default_factory=dict)


@dataclass
class GeneratedBot:
    """A bot that has been (or is being) created by the BotGenerator."""

    bot_id: str
    name: str
    status: BotStatus
    dna: BotDNA
    tools: list
    template_code: str
    config: dict
    created_at: datetime = field(default_factory=datetime.utcnow)


class BotGenerator:
    """Creates, builds, and deploys bots on demand."""

    def __init__(self) -> None:
        self._intent_parser = IntentParser()
        self._tool_db = ToolDB()
        self._bots: dict[str, GeneratedBot] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def create_bot(
        self,
        name: str,
        purpose: str = "",
        industry: str = "",
        revenue_model: Optional[list] = None,
    ) -> GeneratedBot:
        """Main bot creation entry point."""
        if not name:
            raise BotGeneratorError("Bot name must not be empty.")

        if not purpose:
            purpose = f"Automated bot for {industry or 'general'} use-cases."

        # Detect industry if not supplied
        if not industry:
            parsed = self._intent_parser.parse(purpose)
            industry = parsed.industry.value
        else:
            industry = industry.lower()

        tools = self._tool_db.inject_tools(name, industry)
        tool_names = [t.name for t in tools]

        dna = BotDNA(
            name=name,
            purpose=purpose,
            industry=industry,
            revenue_model=revenue_model or ["service_fee"],
            apis=[t.api_endpoint for t in tools if t.api_endpoint],
            automation_level="medium",
            target_user="general_user",
        )

        template_code = self.generate_template(name, industry)
        bot_id = str(uuid.uuid4())

        bot = GeneratedBot(
            bot_id=bot_id,
            name=name,
            status=BotStatus.PENDING,
            dna=dna,
            tools=tool_names,
            template_code=template_code,
            config={"industry": industry, "tools": tool_names},
        )
        self._bots[bot_id] = bot
        return bot

    def generate_template(self, bot_name: str, industry: str) -> str:
        """Generate starter Python code for a bot."""
        cls = "".join(w.capitalize() for w in bot_name.replace("-", "_").split("_"))
        return (
            f'"""Auto-generated bot: {bot_name} (industry={industry})"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            "\n"
            f"class {cls}:\n"
            f'    """Bot generated by BuddyCore for the {industry} industry."""\n'
            "\n"
            "    def __init__(self) -> None:\n"
            f'        self.name = "{bot_name}"\n'
            f'        self.industry = "{industry}"\n'
            "\n"
            "    def run(self, payload: dict) -> dict:\n"
            '        return {"status": "ok", "bot": self.name}\n'
        )

    def build(self, bot_id: str) -> GeneratedBot:
        """Transition a PENDING bot to READY."""
        bot = self._get_or_raise(bot_id)
        if bot.status not in (BotStatus.PENDING, BotStatus.BUILDING):
            raise BotGeneratorError(
                f"Cannot build bot with status {bot.status.value}."
            )
        bot.status = BotStatus.BUILDING
        # Simulate build work
        bot.status = BotStatus.READY
        return bot

    def deploy(self, bot_id: str) -> GeneratedBot:
        """Transition a READY bot to DEPLOYED."""
        bot = self._get_or_raise(bot_id)
        if bot.status != BotStatus.READY:
            raise BotGeneratorError(
                f"Cannot deploy bot with status {bot.status.value}."
            )
        bot.status = BotStatus.DEPLOYED
        return bot

    def get_bot(self, bot_id: str) -> Optional[GeneratedBot]:
        """Return a bot by ID, or None."""
        return self._bots.get(bot_id)

    def list_bots(self) -> list[GeneratedBot]:
        """Return all generated bots."""
        return list(self._bots.values())

    def get_stats(self) -> dict:
        """Return statistics about generated bots."""
        bots = list(self._bots.values())
        counts = {s.value: 0 for s in BotStatus}
        for b in bots:
            counts[b.status.value] += 1
        return {
            "total": len(bots),
            "by_status": counts,
            "industries": list({b.dna.industry for b in bots}),
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_or_raise(self, bot_id: str) -> GeneratedBot:
        bot = self._bots.get(bot_id)
        if bot is None:
            raise BotGeneratorError(f"Bot '{bot_id}' not found.")
        return bot
