# BotBase 2.0 — Core class for all bots in DreamCo OS.
# Adheres to the GLOBAL AI SOURCES FLOW framework — see framework/global_ai_sources_flow.py
#
# Provides:
#   - Bot lifecycle control  (start / stop / pause / resume)
#   - Core engines           (RevenueEngine, AutomationEngine, MonetizationHooks)
#   - Shared AI memory       (DreamCore)
#   - Crash-safe execution   (CrashGuard)
#   - Dashboard metrics      (get_status)

import datetime
import traceback


class RevenueEngine:
    """Tracks and projects revenue generated by a bot."""

    def __init__(self):
        self.total_revenue = 0.0
        self.transactions = []

    def record_transaction(self, amount: float, description: str = "") -> None:
        """Record a revenue transaction."""
        self.total_revenue += amount
        self.transactions.append({
            "amount": amount,
            "description": description,
            "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        })

    def get_summary(self) -> dict:
        return {
            "total_revenue": self.total_revenue,
            "transaction_count": len(self.transactions),
        }


class AutomationEngine:
    """Manages automation hooks and scheduled tasks for a bot."""

    def __init__(self):
        self.hooks = []
        self.tasks_completed = 0

    def register_hook(self, hook_fn) -> None:
        """Register a callable as an automation hook."""
        self.hooks.append(hook_fn)

    def run_hooks(self, context: dict = None) -> None:
        """Execute all registered automation hooks."""
        context = context or {}
        for hook in self.hooks:
            hook(context)
        self.tasks_completed += len(self.hooks)

    def get_summary(self) -> dict:
        return {
            "registered_hooks": len(self.hooks),
            "tasks_completed": self.tasks_completed,
        }


class MonetizationHooks:
    """Provides pluggable monetization callbacks (ads, upsells, referrals, etc.)."""

    def __init__(self):
        self._hooks = {}

    def register(self, event: str, callback) -> None:
        """Register a monetization callback for a named event."""
        self._hooks.setdefault(event, []).append(callback)

    def trigger(self, event: str, payload: dict = None) -> None:
        """Trigger all callbacks registered for an event."""
        payload = payload or {}
        for cb in self._hooks.get(event, []):
            cb(payload)

    def get_summary(self) -> dict:
        return {event: len(cbs) for event, cbs in self._hooks.items()}


class DreamCore:
    """
    Shared AI memory store for cross-bot data and training signals.

    ``_shared_memory`` is intentionally a class-level dict so that every bot
    instance (and every subclass) accesses the same namespace.  This makes
    ``DreamCore`` a lightweight singleton.
    """

    _shared_memory: dict = {}

    @classmethod
    def store(cls, key: str, value) -> None:
        """Save a value to the shared memory."""
        cls._shared_memory[key] = value

    @classmethod
    def retrieve(cls, key: str, default=None):
        """Retrieve a value from the shared memory."""
        return cls._shared_memory.get(key, default)

    @classmethod
    def all(cls) -> dict:
        """Return a copy of the entire shared memory."""
        return dict(cls._shared_memory)


class CrashGuard:
    """Centralized error handler that ensures bot stability on exceptions."""

    def __init__(self):
        self.error_log = []

    def safe_run(self, fn, *args, **kwargs):
        """Execute *fn* safely, logging any exception instead of crashing."""
        try:
            return fn(*args, **kwargs)
        except Exception as exc:
            entry = {
                "error": str(exc),
                "traceback": traceback.format_exc(),
                "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            }
            self.error_log.append(entry)
            return None

    def get_summary(self) -> dict:
        return {"total_errors": len(self.error_log), "errors": list(self.error_log)}


class BotBase:
    """
    BotBase 2.0 — foundation class for every bot in DreamCo OS.

    Subclass this and override ``run()`` to implement bot-specific logic.
    All lifecycle, revenue, automation, monetization, memory, and crash-guard
    capabilities are available out-of-the-box.
    """

    def __init__(self, bot_name: str = "UnnamedBot"):
        self.bot_name = bot_name
        self._state = "stopped"
        self._started_at = None
        self._stopped_at = None

        self.revenue_engine = RevenueEngine()
        self.automation_engine = AutomationEngine()
        self.monetization_hooks = MonetizationHooks()
        self.dream_core = DreamCore
        self.crash_guard = CrashGuard()

    def start(self) -> None:
        """Start the bot and invoke ``run()`` inside CrashGuard."""
        if self._state == "running":
            print(f"[{self.bot_name}] Already running.")
            return
        self._state = "running"
        self._started_at = datetime.datetime.now(datetime.timezone.utc)
        print(f"[{self.bot_name}] Starting...")
        self.crash_guard.safe_run(self.run)

    def stop(self) -> None:
        """Stop the bot."""
        self._state = "stopped"
        self._stopped_at = datetime.datetime.now(datetime.timezone.utc)
        print(f"[{self.bot_name}] Stopped.")

    def pause(self) -> None:
        """Pause the bot."""
        if self._state != "running":
            print(f"[{self.bot_name}] Cannot pause — bot is not running.")
            return
        self._state = "paused"
        print(f"[{self.bot_name}] Paused.")

    def resume(self) -> None:
        """Resume a paused bot."""
        if self._state != "paused":
            print(f"[{self.bot_name}] Cannot resume — bot is not paused.")
            return
        self._state = "running"
        print(f"[{self.bot_name}] Resumed.")

    def run(self) -> None:
        """Main bot logic. Override in every subclass."""
        self.automation_engine.run_hooks()

    def get_status(self) -> dict:
        """Return a metrics snapshot suitable for dashboard display."""
        return {
            "bot_name": self.bot_name,
            "state": self._state,
            "started_at": self._started_at.isoformat() if self._started_at else None,
            "stopped_at": self._stopped_at.isoformat() if self._stopped_at else None,
            "revenue": self.revenue_engine.get_summary(),
            "automation": self.automation_engine.get_summary(),
            "monetization": self.monetization_hooks.get_summary(),
            "crash_guard": self.crash_guard.get_summary(),
            "dream_core_keys": list(self.dream_core.all().keys()),
        }
