[pytest]
markers =
    app_bot: marks tests for App_bots category
    business_bot: marks tests for Business_bots category
    fiverr_bot: marks tests for Fiverr_bots category
    marketing_bot: marks tests for Marketing_bots category
    occupational_bot: marks tests for Occupational_bots category
    real_estate_bot: marks tests for Real_Estate_bots category
