"""
GlobalSourcesAIBot — Model Registry

Catalogs:
  1. TOP_100_USE_CASES — 100 AI use-case categories, each with the 5 best-known
     AI models/platforms and the primary routing tags used by the TaskRouter.
  2. TOP_100_AI_MODELS — 100 global AI models with metadata (provider, type,
     strengths, API endpoint hint, and cost tier).

This registry is the single source of truth consumed by the TaskRouter and
BenchmarkEngine.  All data is static/hardcoded here so the bot works without
any external API calls; live scoring is layered on top by the BenchmarkEngine.

GLOBAL AI SOURCES FLOW: This module adheres to the Dreamcobots GLOBAL AI
SOURCES FLOW framework pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class UseCase:
    """One of the 100 AI use-case categories."""
    id: int
    name: str
    description: str
    tags: list[str]
    top_models: list[str]  # model IDs (keys in TOP_100_AI_MODELS)


@dataclass
class AIModel:
    """A single AI model / platform entry."""
    model_id: str
    display_name: str
    provider: str
    model_type: str          # llm, image, video, voice, code, agent, search, …
    strengths: list[str]     # task tags where this model excels
    api_endpoint_hint: str   # e.g. "https://api.openai.com/v1/chat/completions"
    cost_tier: str           # free | low | medium | high | enterprise
    context_window_k: Optional[int] = None   # thousands of tokens, None if N/A
    is_open_source: bool = False
    notes: str = ""


# ---------------------------------------------------------------------------
# Top-100 AI Use-Cases
# ---------------------------------------------------------------------------

TOP_100_USE_CASES: list[UseCase] = [
    UseCase(1,  "Writing",              "Emails, blogs, scripts, captions, reports",
            ["writing", "text", "content"],
            ["chatgpt", "claude", "jasper", "copy_ai", "writesonic"]),
    UseCase(2,  "Research",             "Summaries, fact-finding, comparisons, citations, analysis",
            ["research", "analysis", "search"],
            ["perplexity", "chatgpt_deep_research", "elicit", "consensus", "gemini"]),
    UseCase(3,  "Coding",               "Debugging, app building, automation, code review, APIs",
            ["coding", "debugging", "automation"],
            ["claude_code", "github_copilot", "cursor", "chatgpt", "gemini_code"]),
    UseCase(4,  "Customer Support",     "Chatbots, FAQs, ticket routing, voice agents, CRM replies",
            ["customer_support", "chatbot", "crm"],
            ["intercom_ai", "zendesk_ai", "chatgpt", "claude", "drift"]),
    UseCase(5,  "Education",            "Tutoring, quizzes, explanations, flashcards, lesson plans",
            ["education", "tutoring", "learning"],
            ["khanmigo", "chatgpt", "claude", "gemini", "socratic"]),
    UseCase(6,  "Image Generation",     "Art, logos, ads, mockups, concept designs",
            ["image_generation", "design", "art"],
            ["midjourney", "dalle3", "flux", "stable_diffusion", "firefly"]),
    UseCase(7,  "Video Creation",       "Editing, captions, avatars, effects, trailers",
            ["video", "editing", "animation"],
            ["sora", "runway", "pika", "veo", "dream_machine"]),
    UseCase(8,  "Music Production",     "Beats, mastering, lyrics, vocals, composition",
            ["music", "audio", "creativity"],
            ["suno", "udio", "aiva", "soundraw", "boomy"]),
    UseCase(9,  "Data Analysis",        "Dashboards, predictions, trends, spreadsheets, insights",
            ["data", "analytics", "prediction"],
            ["tableau_ai", "power_bi_copilot", "chatgpt", "claude", "hex_ai"]),
    UseCase(10, "Business Automation",  "Workflows, scheduling, invoices, CRM tasks, approvals",
            ["automation", "workflow", "business"],
            ["zapier_ai", "make_ai", "uipath", "salesforce_einstein", "hubspot_breeze"]),
    UseCase(11, "Social Media Growth",  "Posts, hashtags, analytics, engagement, calendars",
            ["social_media", "content", "marketing"],
            ["canva_ai", "chatgpt", "buffer_ai", "hootsuite_ai", "grok"]),
    UseCase(12, "Marketing",            "Ad copy, funnels, SEO, campaigns, targeting",
            ["marketing", "advertising", "seo"],
            ["jasper", "copy_ai", "hubspot_ai", "claude", "chatgpt"]),
    UseCase(13, "Sales",                "Lead scoring, outreach, follow-ups, proposals, forecasting",
            ["sales", "crm", "outreach"],
            ["apollo_ai", "salesforce_einstein", "hubspot_breeze", "lavender", "gong"]),
    UseCase(14, "Financial Planning",   "Budgeting, investing, forecasting, taxes, alerts",
            ["finance", "forecasting", "investing"],
            ["bloomberg_gpt", "chatgpt", "claude", "gemini", "kasisto"]),
    UseCase(15, "Healthcare Assistance","Diagnostics, notes, scheduling, imaging, patient triage",
            ["healthcare", "medical", "diagnostics"],
            ["med_palm", "ms_dragon", "suki_ai", "nabla", "chatgpt"]),
    UseCase(16, "Mental Wellness",      "Journaling, coaching, mood tracking, meditation, support",
            ["wellness", "mental_health", "coaching"],
            ["woebot", "replika", "pi_ai", "character_ai", "chatgpt"]),
    UseCase(17, "Translation",          "Text translation, voice translation, subtitles, localization",
            ["translation", "localization", "language"],
            ["deepl", "chatgpt", "gemini", "claude", "google_translate_ai"]),
    UseCase(18, "Productivity",         "To-do lists, reminders, prioritization, focus tools",
            ["productivity", "organization", "scheduling"],
            ["notion_ai", "clickup_ai", "ms_copilot", "gemini_workspace", "slack_ai"]),
    UseCase(19, "Gaming",               "NPCs, strategy guides, mods, procedural worlds, matchmaking",
            ["gaming", "npc", "creative"],
            ["nvidia_ace", "inworld", "unity_muse", "roblox_ai", "convai"]),
    UseCase(20, "Shopping",             "Recommendations, price tracking, reviews, sizing",
            ["ecommerce", "shopping", "recommendations"],
            ["amazon_rufus", "chatgpt", "gemini", "perplexity", "klarna_ai"]),
    UseCase(21, "Cybersecurity",        "Threat detection, fraud prevention, monitoring, risk analysis",
            ["cybersecurity", "security", "threat_detection"],
            ["crowdstrike_ai", "darktrace", "sentinelone", "ms_security_ai", "ibm_watson"]),
    UseCase(22, "Legal Work",           "Contracts, summaries, compliance, research, document review",
            ["legal", "compliance", "contracts"],
            ["harvey_ai", "cocounsel", "claude", "chatgpt", "lexis_ai"]),
    UseCase(23, "Recruiting",           "Resume screening, interview prep, job matching, outreach",
            ["recruiting", "hr", "hiring"],
            ["linkedin_ai", "hirevue", "eightfold_ai", "workday_ai", "paradox"]),
    UseCase(24, "HR Management",        "Training, evaluations, surveys, scheduling, policy",
            ["hr", "training", "management"],
            ["workday_ai", "ms_copilot", "chatgpt", "claude", "lattice_ai"]),
    UseCase(25, "Real Estate",          "Listings, valuations, virtual staging, market trends",
            ["real_estate", "property", "valuation"],
            ["zillow_ai", "house_canary", "chatgpt", "realtor_ai", "redfin_ai"]),
    UseCase(26, "Architecture",         "Floor plans, renders, simulations, material planning",
            ["architecture", "design", "cad"],
            ["autodesk_ai", "midjourney", "stable_diffusion", "rhino_ai", "testfit"]),
    UseCase(27, "Engineering",          "CAD support, simulations, optimization, diagnostics",
            ["engineering", "simulation", "cad"],
            ["nvidia_omniverse", "matlab_ai", "ms_copilot", "claude", "gemini"]),
    UseCase(28, "Scientific Research",  "Modeling, protein analysis, simulations, paper summaries",
            ["science", "research", "simulation"],
            ["alphafold", "elicit", "consensus", "chatgpt", "gemini"]),
    UseCase(29, "Manufacturing",        "Robotics, quality checks, predictive maintenance, inventory",
            ["manufacturing", "robotics", "automation"],
            ["siemens_ai", "nvidia_isaac", "ibm_watson", "azure_ai", "uipath"]),
    UseCase(30, "Logistics",            "Route planning, fleet tracking, warehouse automation",
            ["logistics", "routing", "supply_chain"],
            ["flexport_ai", "amazon_ai", "oracle_ai", "sap_ai", "fourkites"]),
    UseCase(31, "Agriculture",          "Crop monitoring, irrigation control, pest detection",
            ["agriculture", "iot", "prediction"],
            ["john_deere_ai", "climate_fieldview", "dronedeploy_ai", "ibm_watson", "prospera"]),
    UseCase(32, "Weather Forecasting",  "Prediction models, alerts, climate analysis",
            ["weather", "prediction", "climate"],
            ["ibm_watson", "nvidia_earth2", "climate_gpt", "google_ai", "tomorrow_io"]),
    UseCase(33, "Smart Homes",          "Voice control, automation, security, energy saving",
            ["smart_home", "iot", "automation"],
            ["alexa_ai", "google_nest_ai", "samsung_smartthings", "home_assistant_ai", "apple_home_ai"]),
    UseCase(34, "Personal Assistants",  "Scheduling, reminders, travel booking, calls",
            ["assistant", "scheduling", "productivity"],
            ["chatgpt", "claude", "gemini", "ms_copilot", "pi_ai"]),
    UseCase(35, "Voice Generation",     "Audiobooks, dubbing, assistants, narration, accessibility",
            ["voice", "tts", "audio"],
            ["elevenlabs", "playht", "hume", "openai_voice", "resemble"]),
    UseCase(36, "Speech Recognition",   "Dictation, meeting notes, commands, subtitles",
            ["speech", "stt", "transcription"],
            ["whisper", "otter_ai", "fireflies_ai", "ms_copilot", "google_speech"]),
    UseCase(37, "Search Enhancement",   "Semantic search, recommendations, filtering, indexing",
            ["search", "semantic", "discovery"],
            ["perplexity", "gemini_search", "grok_search", "you_ai", "chatgpt_search"]),
    UseCase(38, "Creativity",           "Brainstorming, ideation, storytelling, design concepts",
            ["creativity", "ideation", "writing"],
            ["chatgpt", "claude", "grok", "gemini", "midjourney"]),
    UseCase(39, "Resume Building",      "Formatting, optimization, cover letters, ATS scoring",
            ["resume", "career", "writing"],
            ["teal_ai", "rezi", "chatgpt", "kickresume_ai", "canva_ai"]),
    UseCase(40, "Interview Preparation","Mock interviews, answers, confidence coaching",
            ["interview", "career", "coaching"],
            ["chatgpt", "claude", "final_round_ai", "huru", "gemini"]),
    UseCase(41, "Language Learning",    "Pronunciation, grammar, vocabulary, conversation, quizzes",
            ["language", "education", "translation"],
            ["duolingo_max", "chatgpt", "gemini", "claude", "memrise_ai"]),
    UseCase(42, "Fitness Coaching",     "Workout plans, nutrition, tracking, recovery, motivation",
            ["fitness", "health", "coaching"],
            ["freeletics_ai", "fitbod", "chatgpt", "whoop_ai", "garmin_ai"]),
    UseCase(43, "Nutrition Planning",   "Meal plans, calorie tracking, recipes, grocery lists",
            ["nutrition", "health", "planning"],
            ["chatgpt", "noom_ai", "myfitnesspal_ai", "gemini", "lifesum"]),
    UseCase(44, "Travel Planning",      "Itineraries, budgeting, translation, recommendations",
            ["travel", "planning", "recommendations"],
            ["hopper_ai", "chatgpt", "gemini", "expedia_ai", "guidgeek"]),
    UseCase(45, "Navigation",           "Traffic routing, maps, ride optimization, parking",
            ["navigation", "routing", "maps"],
            ["google_maps_ai", "waze_ai", "tesla_ai", "apple_maps_ai", "here_ai"]),
    UseCase(46, "Banking",              "Fraud detection, automation, customer support, risk scoring",
            ["banking", "finance", "fraud_detection"],
            ["bloomberg_gpt", "ms_copilot", "gemini", "chatgpt", "kasisto"]),
    UseCase(47, "Insurance",            "Claims processing, fraud detection, risk analysis, pricing",
            ["insurance", "risk", "automation"],
            ["lemonade_ai", "tractable", "ccc_ai", "guidewire_ai", "ibm_watson"]),
    UseCase(48, "Cryptocurrency",       "Trading bots, analytics, security alerts, portfolio tracking",
            ["crypto", "trading", "blockchain"],
            ["chain_gpt", "arkham_ai", "grok", "chatgpt", "nansen_ai"]),
    UseCase(49, "Stock Trading",        "Predictions, chart analysis, bots, alerts, sentiment analysis",
            ["trading", "finance", "prediction"],
            ["bloomberg_gpt", "kavout", "trendspider", "trade_ideas_ai", "chatgpt"]),
    UseCase(50, "Content Creation",     "Blogs, podcasts, videos, graphics, newsletters",
            ["content", "writing", "media"],
            ["chatgpt", "claude", "jasper", "canva_ai", "descript"]),
    UseCase(51, "Podcasting",           "Editing, scripts, transcription, audio cleanup, publishing",
            ["podcast", "audio", "editing"],
            ["descript", "adobe_ai", "elevenlabs", "chatgpt", "capcut_ai"]),
    UseCase(52, "Journalism",           "Research, drafting, transcription, summaries, verification",
            ["journalism", "writing", "research"],
            ["chatgpt", "claude", "gemini", "perplexity", "bloomberg_gpt"]),
    UseCase(53, "Book Writing",         "Plotting, editing, outlines, character building, formatting",
            ["writing", "creativity", "book"],
            ["claude", "chatgpt", "sudowrite", "novel_ai", "gemini"]),
    UseCase(54, "Scriptwriting",        "Dialogue, storyboarding, pacing, scene generation",
            ["scriptwriting", "writing", "creativity"],
            ["final_draft_ai", "claude", "chatgpt", "gemini", "sudowrite"]),
    UseCase(55, "Photography",          "Editing, enhancement, object removal, color correction",
            ["photography", "image", "editing"],
            ["photoshop_ai", "luminar_ai", "canva_ai", "firefly", "topaz_labs"]),
    UseCase(56, "Film Production",      "CGI, editing, dubbing, previsualization, scheduling",
            ["film", "video", "cgi"],
            ["sora", "runway", "veo", "adobe_ai", "descript"]),
    UseCase(57, "Animation",            "Motion generation, lip-syncing, rendering, character design",
            ["animation", "video", "design"],
            ["runway", "adobe_ai", "pika", "blender_ai", "wonder_studio"]),
    UseCase(58, "Graphic Design",       "Branding, typography, layouts, mockups, UI assets",
            ["graphic_design", "design", "branding"],
            ["midjourney", "canva_ai", "firefly", "stable_diffusion", "figma_ai"]),
    UseCase(59, "UI/UX Design",         "Wireframes, testing, prototypes, accessibility, flows",
            ["uiux", "design", "prototyping"],
            ["figma_ai", "v0", "galileo_ai", "uizard", "framer_ai"]),
    UseCase(60, "App Development",      "Frontend, backend, debugging, deployment, testing",
            ["app_development", "coding", "deployment"],
            ["replit_ai", "bolt_new", "lovable", "cursor", "v0"]),
    UseCase(61, "Website Building",     "Templates, SEO, chatbots, ecommerce, optimization",
            ["website", "coding", "seo"],
            ["wix_ai", "framer_ai", "v0", "bolt_new", "lovable"]),
    UseCase(62, "Ecommerce",            "Product descriptions, recommendations, automation, ads",
            ["ecommerce", "marketing", "automation"],
            ["shopify_magic", "amazon_ai", "chatgpt", "klaviyo_ai", "jasper"]),
    UseCase(63, "SEO Optimization",     "Keywords, content briefs, audits, backlinks, rankings",
            ["seo", "marketing", "content"],
            ["surfer_ai", "jasper", "gemini", "chatgpt", "frase"]),
    UseCase(64, "Email Marketing",      "Campaigns, segmentation, personalization, automation",
            ["email", "marketing", "automation"],
            ["superhuman_ai", "gmail_gemini", "outlook_copilot", "claude", "chatgpt"]),
    UseCase(65, "Advertising",          "Creative testing, audience targeting, copywriting, bidding",
            ["advertising", "marketing", "creative"],
            ["adcreative_ai", "canva_ai", "jasper", "midjourney", "firefly"]),
    UseCase(66, "Branding",             "Logos, slogans, identity systems, strategy, messaging",
            ["branding", "design", "marketing"],
            ["midjourney", "canva_ai", "looka", "firefly", "chatgpt"]),
    UseCase(67, "Public Relations",     "Press releases, monitoring, sentiment tracking, outreach",
            ["pr", "marketing", "communication"],
            ["chatgpt", "claude", "gemini", "jasper", "perplexity"]),
    UseCase(68, "Event Planning",       "Scheduling, budgeting, ticketing, guest management",
            ["events", "planning", "scheduling"],
            ["chatgpt", "claude", "notion_ai", "gemini", "ms_copilot"]),
    UseCase(69, "Religion/Spirituality","Study aids, devotionals, meditation, discussions",
            ["spirituality", "wellness", "education"],
            ["chatgpt", "bible_ai", "hallow_ai", "pray_ai", "claude"]),
    UseCase(70, "Accessibility",        "Screen readers, captions, voice control, translation",
            ["accessibility", "voice", "translation"],
            ["seeing_ai", "be_my_eyes", "live_caption_ai", "voice_access_ai", "chatgpt"]),
    UseCase(71, "Elder Care",           "Medication reminders, monitoring, companionship, alerts",
            ["eldercare", "health", "assistant"],
            ["elliq", "carepredict", "chatgpt", "alexa_ai", "replika"]),
    UseCase(72, "Child Education",      "Tutoring, games, personalized learning, reading help",
            ["education", "children", "learning"],
            ["khanmigo", "duolingo_max", "chatgpt", "gemini", "abcmouse_ai"]),
    UseCase(73, "Robotics",             "Navigation, manipulation, automation, sensing, autonomy",
            ["robotics", "automation", "engineering"],
            ["nvidia_isaac", "figure_ai", "tesla_optimus", "sanctuary_ai", "boston_dynamics_ai"]),
    UseCase(74, "Space Exploration",    "Satellite analysis, rover control, simulations, astronomy",
            ["space", "science", "simulation"],
            ["nasa_ai", "ibm_watson", "nvidia_omniverse", "spacex_ai", "esa_ai"]),
    UseCase(75, "Military Defense",     "Surveillance, simulations, logistics, cybersecurity",
            ["defense", "security", "simulation"],
            ["palantir_aip", "anduril", "shield_ai", "lockheed_ai", "nvidia"]),
    UseCase(76, "Disaster Response",    "Mapping, prediction, rescue coordination, communication",
            ["disaster", "emergency", "prediction"],
            ["one_concern", "ibm_watson", "palantir", "dronedeploy_ai", "google_crisis_ai"]),
    UseCase(77, "Environmental Protection","Pollution monitoring, wildlife tracking, climate modeling",
            ["environment", "climate", "monitoring"],
            ["ibm_watson", "nvidia_earth2", "climate_gpt", "google_ai", "tomorrow_io"]),
    UseCase(78, "Energy Optimization",  "Smart grids, usage forecasting, battery management",
            ["energy", "iot", "prediction"],
            ["tesla_energy_ai", "grid_ai", "siemens_ai", "schneider_electric_ai", "ibm_watson"]),
    UseCase(79, "Construction",         "Project planning, safety checks, estimation, scheduling",
            ["construction", "planning", "automation"],
            ["procore_ai", "openspace_ai", "autodesk_ai", "buildots", "dronedeploy_ai"]),
    UseCase(80, "Telecom",              "Network optimization, fraud prevention, routing, monitoring",
            ["telecom", "networking", "optimization"],
            ["nokia_ai", "ericsson_ai", "aws_ai", "azure_ai", "ibm_watson"]),
    UseCase(81, "Customer Personalization","Recommendations, dynamic pricing, tailored content",
            ["personalization", "recommendations", "ecommerce"],
            ["salesforce_einstein", "dynamic_yield", "chatgpt", "claude", "gemini"]),
    UseCase(82, "Knowledge Management", "Internal search, documentation, FAQs, enterprise assistants",
            ["knowledge", "search", "documentation"],
            ["notion_ai", "guru_ai", "glean", "ms_copilot", "confluence_ai"]),
    UseCase(83, "Workflow Management",  "Pipelines, approvals, integrations, reminders, reporting",
            ["workflow", "automation", "business"],
            ["zapier_ai", "make_ai", "uipath", "n8n_ai", "pipedream_ai"]),
    UseCase(84, "Collaboration",        "Shared workspaces, brainstorming, meeting summaries",
            ["collaboration", "productivity", "communication"],
            ["notion_ai", "ms_copilot", "google_workspace_ai", "slack_ai", "miro_ai"]),
    UseCase(85, "Meeting Assistance",   "Notes, summaries, action items, transcription, scheduling",
            ["meetings", "transcription", "productivity"],
            ["otter_ai", "fireflies_ai", "ms_copilot", "gemini", "notion_ai"]),
    UseCase(86, "Time Management",      "Calendars, prioritization, reminders, automation",
            ["time_management", "productivity", "scheduling"],
            ["ms_copilot", "notion_ai", "google_workspace_ai", "chatgpt", "reclaim_ai"]),
    UseCase(87, "Decision Support",     "Simulations, forecasting, recommendations, risk analysis",
            ["decision", "forecasting", "analysis"],
            ["chatgpt", "claude", "gemini", "perplexity", "ibm_watson"]),
    UseCase(88, "Predictive Analytics", "Demand forecasting, behavior prediction, maintenance, churn",
            ["prediction", "analytics", "data"],
            ["datarobot", "h2o_ai", "aws_sagemaker", "azure_ai", "google_vertex"]),
    UseCase(89, "Fraud Detection",      "Banking fraud, identity theft, ecommerce scams, spam",
            ["fraud_detection", "security", "banking"],
            ["visa_ai", "mastercard_ai", "stripe_radar", "paypal_ai", "aws_fraud_detector"]),
    UseCase(90, "Identity Verification","Facial recognition, biometrics, authentication, document checks",
            ["identity", "security", "biometrics"],
            ["ms_azure_face", "aws_rekognition", "ocrolus", "jumio", "onfido"]),
    UseCase(91, "Smart Cities",         "Traffic systems, surveillance, utilities, transit optimization",
            ["smart_city", "iot", "optimization"],
            ["nvidia_metropolis", "cisco_ai", "ibm_watson", "siemens_ai", "google_urban_ai"]),
    UseCase(92, "Transportation",       "Autonomous driving, dispatching, route optimization",
            ["transportation", "routing", "autonomous"],
            ["tesla_fsd", "waymo_ai", "nvidia_drive", "cruise_ai", "mobileye"]),
    UseCase(93, "Autonomous Vehicles",  "Navigation, safety systems, sensors, mapping",
            ["autonomous", "navigation", "engineering"],
            ["tesla_fsd", "waymo_ai", "nvidia_drive", "cruise_ai", "mobileye"]),
    UseCase(94, "Drone Technology",     "Delivery, surveillance, mapping, inspections, agriculture",
            ["drone", "robotics", "mapping"],
            ["skydio_ai", "dji_ai", "nvidia_jetson", "shield_ai", "anduril"]),
    UseCase(95, "Virtual Reality",      "NPCs, simulations, immersive training, gaming, collaboration",
            ["vr", "gaming", "simulation"],
            ["meta_ai", "nvidia_ace", "inworld", "unity_muse", "apple_vision_ai"]),
    UseCase(96, "Augmented Reality",    "Navigation overlays, education, retail previews, maintenance",
            ["ar", "design", "education"],
            ["snap_ai", "apple_vision_ai", "meta_ai", "niantic_ai", "google_ar_ai"]),
    UseCase(97, "Digital Companions",   "Conversation, coaching, companionship, entertainment",
            ["companion", "conversation", "wellness"],
            ["character_ai", "replika", "nomi_ai", "pi_ai", "chai"]),
    UseCase(98, "Entertainment",        "Recommendations, streaming personalization, interactive media",
            ["entertainment", "recommendations", "media"],
            ["chatgpt", "claude", "gemini", "character_ai", "midjourney"]),
    UseCase(99, "Problem Solving",      "Optimization, simulations, diagnostics, brainstorming",
            ["problem_solving", "optimization", "research"],
            ["chatgpt", "claude", "gemini", "perplexity", "wolfram_ai"]),
    UseCase(100,"Making Money",         "Side hustles, automation agencies, AI SaaS, content monetization",
            ["monetization", "business", "automation"],
            ["chatgpt", "claude", "grok", "gemini", "midjourney"]),
]


# ---------------------------------------------------------------------------
# Top-100 Global AI Models
# ---------------------------------------------------------------------------

TOP_100_AI_MODELS: dict[str, AIModel] = {

    # ── General-purpose LLMs ──────────────────────────────────────────────
    "chatgpt": AIModel("chatgpt", "ChatGPT (GPT-4o)", "OpenAI", "llm",
        ["writing", "research", "coding", "assistant", "analysis"],
        "https://api.openai.com/v1/chat/completions", "medium", 128),
    "claude": AIModel("claude", "Claude 3 Opus", "Anthropic", "llm",
        ["writing", "coding", "research", "analysis", "legal"],
        "https://api.anthropic.com/v1/messages", "medium", 200),
    "gemini": AIModel("gemini", "Gemini 1.5 Pro", "Google", "llm",
        ["research", "coding", "analysis", "multimodal", "assistant"],
        "https://generativelanguage.googleapis.com/v1beta/models", "medium", 1000),
    "grok": AIModel("grok", "Grok 3", "xAI", "llm",
        ["research", "writing", "analysis", "social_media"],
        "https://api.x.ai/v1/chat/completions", "medium", 128),
    "meta_ai": AIModel("meta_ai", "Meta AI (Llama 3)", "Meta", "llm",
        ["writing", "coding", "research", "assistant"],
        "https://www.meta.ai/api", "free", 128),

    # ── Coding specialists ────────────────────────────────────────────────
    "claude_code": AIModel("claude_code", "Claude Code", "Anthropic", "code",
        ["coding", "debugging", "app_development", "code_review"],
        "https://api.anthropic.com/v1/messages", "high", 200),
    "github_copilot": AIModel("github_copilot", "GitHub Copilot", "GitHub/OpenAI", "code",
        ["coding", "debugging", "app_development"],
        "https://api.github.com/copilot", "low", 32),
    "cursor": AIModel("cursor", "Cursor AI", "Cursor", "code",
        ["coding", "debugging", "app_development"],
        "https://cursor.sh/api", "low", 128),
    "gemini_code": AIModel("gemini_code", "Gemini Code Assist", "Google", "code",
        ["coding", "debugging", "app_development"],
        "https://generativelanguage.googleapis.com/v1beta/models", "low", 1000),
    "replit_ai": AIModel("replit_ai", "Replit AI", "Replit", "code",
        ["coding", "app_development", "deployment"],
        "https://replit.com/api", "low", 32),

    # ── Open-source LLMs ─────────────────────────────────────────────────
    "llama": AIModel("llama", "Llama 3.3", "Meta", "llm",
        ["writing", "coding", "research", "assistant"],
        "https://huggingface.co/meta-llama", "free", 128, is_open_source=True),
    "mistral": AIModel("mistral", "Mistral Large", "Mistral AI", "llm",
        ["writing", "coding", "research", "multilingual"],
        "https://api.mistral.ai/v1/chat/completions", "low", 128, is_open_source=True),
    "deepseek": AIModel("deepseek", "DeepSeek V3", "DeepSeek", "llm",
        ["coding", "research", "analysis"],
        "https://api.deepseek.com/v1/chat/completions", "free", 64, is_open_source=True),
    "qwen": AIModel("qwen", "Qwen 2.5", "Alibaba", "llm",
        ["coding", "research", "multilingual", "analysis"],
        "https://dashscope.aliyuncs.com/api/v1", "low", 128, is_open_source=True),
    "gemma": AIModel("gemma", "Gemma 2", "Google", "llm",
        ["writing", "coding", "research"],
        "https://huggingface.co/google/gemma", "free", 8, is_open_source=True),

    # ── AI Agents / Autonomous ────────────────────────────────────────────
    "crewai": AIModel("crewai", "CrewAI", "CrewAI", "agent",
        ["automation", "workflow", "multi_agent", "business"],
        "https://api.crewai.com", "medium"),
    "autogen": AIModel("autogen", "AutoGen", "Microsoft", "agent",
        ["automation", "workflow", "multi_agent", "coding"],
        "https://github.com/microsoft/autogen", "free", is_open_source=True),
    "langgraph": AIModel("langgraph", "LangGraph", "LangChain", "agent",
        ["automation", "workflow", "orchestration"],
        "https://api.langchain.com", "low", is_open_source=True),
    "openai_operator": AIModel("openai_operator", "OpenAI Operator", "OpenAI", "agent",
        ["automation", "web_browsing", "business"],
        "https://api.openai.com/v1/agents", "high"),
    "emergent_agent": AIModel("emergent_agent", "Emergent Agent", "Emergent Labs", "agent",
        ["automation", "multi_agent", "workflow"],
        "https://app.emergentmind.com/api", "high"),

    # ── Image generation ─────────────────────────────────────────────────
    "midjourney": AIModel("midjourney", "Midjourney V6", "Midjourney", "image",
        ["image_generation", "design", "art", "branding"],
        "https://api.midjourney.com", "medium"),
    "dalle3": AIModel("dalle3", "DALL·E 3", "OpenAI", "image",
        ["image_generation", "design", "art"],
        "https://api.openai.com/v1/images/generations", "medium"),
    "stable_diffusion": AIModel("stable_diffusion", "Stable Diffusion 3", "Stability AI", "image",
        ["image_generation", "design", "art"],
        "https://api.stability.ai/v2beta/stable-image/generate/core", "low", is_open_source=True),
    "firefly": AIModel("firefly", "Adobe Firefly", "Adobe", "image",
        ["image_generation", "graphic_design", "branding"],
        "https://firefly.adobe.com/api", "medium"),
    "flux": AIModel("flux", "FLUX.1", "Black Forest Labs", "image",
        ["image_generation", "art", "design"],
        "https://api.bfl.ml", "low", is_open_source=True),

    # ── Video generation ─────────────────────────────────────────────────
    "sora": AIModel("sora", "Sora", "OpenAI", "video",
        ["video", "animation", "film"],
        "https://api.openai.com/v1/video", "high"),
    "runway": AIModel("runway", "Runway Gen-3", "Runway", "video",
        ["video", "animation", "film", "editing"],
        "https://api.runwayml.com/v1", "high"),
    "pika": AIModel("pika", "Pika 2.0", "Pika Labs", "video",
        ["video", "animation", "effects"],
        "https://api.pika.art", "medium"),
    "veo": AIModel("veo", "Veo 2", "Google", "video",
        ["video", "animation", "film"],
        "https://deepmind.google/technologies/veo", "high"),
    "dream_machine": AIModel("dream_machine", "Dream Machine", "Luma AI", "video",
        ["video", "animation", "3d"],
        "https://lumalabs.ai/dream-machine/api", "medium"),

    # ── Voice / TTS ───────────────────────────────────────────────────────
    "elevenlabs": AIModel("elevenlabs", "ElevenLabs", "ElevenLabs", "voice",
        ["voice", "tts", "dubbing", "accessibility"],
        "https://api.elevenlabs.io/v1/text-to-speech", "medium"),
    "playht": AIModel("playht", "PlayHT 3.0", "PlayHT", "voice",
        ["voice", "tts", "podcast"],
        "https://api.play.ht/api/v2/tts", "low"),
    "hume": AIModel("hume", "Hume EVI", "Hume AI", "voice",
        ["voice", "emotion", "assistant"],
        "https://api.hume.ai/v0/evi", "medium"),
    "openai_voice": AIModel("openai_voice", "OpenAI Advanced Voice", "OpenAI", "voice",
        ["voice", "tts", "assistant"],
        "https://api.openai.com/v1/audio/speech", "medium"),
    "resemble": AIModel("resemble", "Resemble AI", "Resemble AI", "voice",
        ["voice", "tts", "cloning"],
        "https://app.resemble.ai/api/v2", "medium"),

    # ── Speech recognition / STT ──────────────────────────────────────────
    "whisper": AIModel("whisper", "Whisper", "OpenAI", "stt",
        ["speech", "transcription", "stt"],
        "https://api.openai.com/v1/audio/transcriptions", "low", is_open_source=True),
    "otter_ai": AIModel("otter_ai", "Otter.ai", "Otter.ai", "stt",
        ["transcription", "meetings", "speech"],
        "https://otter.ai/api", "low"),
    "fireflies_ai": AIModel("fireflies_ai", "Fireflies.ai", "Fireflies.ai", "stt",
        ["meetings", "transcription", "productivity"],
        "https://api.fireflies.ai/graphql", "low"),

    # ── Music generation ──────────────────────────────────────────────────
    "suno": AIModel("suno", "Suno v3", "Suno", "music",
        ["music", "audio", "creativity"],
        "https://studio.suno.ai/api", "low"),
    "udio": AIModel("udio", "Udio", "Udio", "music",
        ["music", "audio", "creativity"],
        "https://www.udio.com/api", "low"),
    "aiva": AIModel("aiva", "AIVA", "AIVA", "music",
        ["music", "composition", "film"],
        "https://api.aiva.ai", "medium"),
    "soundraw": AIModel("soundraw", "Soundraw", "Soundraw", "music",
        ["music", "audio", "content"],
        "https://soundraw.io/api", "low"),
    "boomy": AIModel("boomy", "Boomy", "Boomy", "music",
        ["music", "audio", "creativity"],
        "https://api.boomy.com", "free"),

    # ── Research & search ─────────────────────────────────────────────────
    "perplexity": AIModel("perplexity", "Perplexity AI", "Perplexity AI", "search",
        ["research", "search", "analysis", "fact_finding"],
        "https://api.perplexity.ai/chat/completions", "low"),
    "chatgpt_deep_research": AIModel("chatgpt_deep_research", "ChatGPT Deep Research",
        "OpenAI", "search",
        ["research", "analysis", "fact_finding"],
        "https://api.openai.com/v1/chat/completions", "high"),
    "elicit": AIModel("elicit", "Elicit", "Elicit", "search",
        ["research", "science", "analysis"],
        "https://api.elicit.com", "low"),
    "consensus": AIModel("consensus", "Consensus", "Consensus", "search",
        ["research", "science", "fact_finding"],
        "https://api.consensus.app", "low"),
    "you_ai": AIModel("you_ai", "You.com", "You.com", "search",
        ["search", "research", "discovery"],
        "https://api.you.com/search", "free"),

    # ── Marketing / writing ───────────────────────────────────────────────
    "jasper": AIModel("jasper", "Jasper AI", "Jasper", "llm",
        ["writing", "marketing", "seo", "content"],
        "https://api.jasper.ai/v1", "medium"),
    "copy_ai": AIModel("copy_ai", "Copy.ai", "Copy.ai", "llm",
        ["writing", "marketing", "content"],
        "https://api.copy.ai/v1", "low"),
    "writesonic": AIModel("writesonic", "Writesonic", "Writesonic", "llm",
        ["writing", "seo", "marketing"],
        "https://api.writesonic.com/v2", "low"),
    "surfer_ai": AIModel("surfer_ai", "Surfer AI", "Surfer SEO", "llm",
        ["seo", "content", "marketing"],
        "https://api.surferseo.com", "medium"),

    # ── Design / creative ─────────────────────────────────────────────────
    "canva_ai": AIModel("canva_ai", "Canva AI", "Canva", "design",
        ["graphic_design", "branding", "social_media", "presentations"],
        "https://api.canva.com/rest/v1", "free"),
    "figma_ai": AIModel("figma_ai", "Figma AI", "Figma", "design",
        ["uiux", "prototyping", "design"],
        "https://api.figma.com/v1", "medium"),
    "v0": AIModel("v0", "v0 by Vercel", "Vercel", "code",
        ["uiux", "app_development", "website", "frontend"],
        "https://v0.dev/api", "medium"),
    "framer_ai": AIModel("framer_ai", "Framer AI", "Framer", "design",
        ["website", "uiux", "design"],
        "https://api.framer.com", "medium"),

    # ── Automation platforms ──────────────────────────────────────────────
    "zapier_ai": AIModel("zapier_ai", "Zapier AI", "Zapier", "automation",
        ["automation", "workflow", "integration"],
        "https://api.zapier.com/v1", "medium"),
    "make_ai": AIModel("make_ai", "Make AI", "Make", "automation",
        ["automation", "workflow", "integration"],
        "https://api.make.com/v2", "low"),
    "n8n_ai": AIModel("n8n_ai", "n8n AI", "n8n", "automation",
        ["automation", "workflow", "integration"],
        "https://api.n8n.io", "free", is_open_source=True),
    "uipath": AIModel("uipath", "UiPath AI", "UiPath", "automation",
        ["automation", "rpa", "business", "manufacturing"],
        "https://cloud.uipath.com/api", "enterprise"),

    # ── Business / CRM ────────────────────────────────────────────────────
    "salesforce_einstein": AIModel("salesforce_einstein", "Salesforce Einstein",
        "Salesforce", "crm",
        ["crm", "sales", "automation", "analytics"],
        "https://api.salesforce.com/services/apexrest", "enterprise"),
    "hubspot_breeze": AIModel("hubspot_breeze", "HubSpot Breeze AI", "HubSpot", "crm",
        ["crm", "marketing", "sales", "email"],
        "https://api.hubapi.com", "medium"),

    # ── Analytics / data ─────────────────────────────────────────────────
    "tableau_ai": AIModel("tableau_ai", "Tableau AI", "Salesforce/Tableau", "analytics",
        ["data", "analytics", "visualization", "dashboards"],
        "https://api.tableau.com/api", "enterprise"),
    "power_bi_copilot": AIModel("power_bi_copilot", "Power BI Copilot", "Microsoft",
        "analytics",
        ["data", "analytics", "dashboards"],
        "https://api.powerbi.com/v1.0/myorg", "medium"),
    "datarobot": AIModel("datarobot", "DataRobot", "DataRobot", "analytics",
        ["prediction", "analytics", "machine_learning"],
        "https://app.datarobot.com/api/v2", "enterprise"),

    # ── Presentation ─────────────────────────────────────────────────────
    "gamma": AIModel("gamma", "Gamma", "Gamma", "presentation",
        ["presentations", "content", "design"],
        "https://api.gamma.app", "low"),

    # ── Productivity ─────────────────────────────────────────────────────
    "notion_ai": AIModel("notion_ai", "Notion AI", "Notion", "productivity",
        ["productivity", "knowledge", "writing", "meetings"],
        "https://api.notion.com/v1", "low"),
    "ms_copilot": AIModel("ms_copilot", "Microsoft Copilot", "Microsoft", "llm",
        ["productivity", "coding", "writing", "data", "meetings"],
        "https://api.cognitive.microsoft.com", "medium"),
    "slack_ai": AIModel("slack_ai", "Slack AI", "Salesforce/Slack", "productivity",
        ["productivity", "collaboration", "meetings"],
        "https://api.slack.com", "medium"),

    # ── Healthcare ────────────────────────────────────────────────────────
    "med_palm": AIModel("med_palm", "Med-PaLM 2", "Google", "llm",
        ["healthcare", "medical", "diagnostics"],
        "https://cloud.google.com/vertex-ai/docs/generative-ai/medical-palm", "enterprise"),
    "ms_dragon": AIModel("ms_dragon", "Microsoft Dragon Copilot", "Microsoft", "llm",
        ["healthcare", "medical", "transcription"],
        "https://azure.microsoft.com/en-us/services/health-bot", "enterprise"),

    # ── Finance / trading ─────────────────────────────────────────────────
    "bloomberg_gpt": AIModel("bloomberg_gpt", "BloombergGPT", "Bloomberg", "llm",
        ["finance", "trading", "banking", "journalism"],
        "https://api.bloomberg.com", "enterprise"),

    # ── Legal ─────────────────────────────────────────────────────────────
    "harvey_ai": AIModel("harvey_ai", "Harvey AI", "Harvey", "llm",
        ["legal", "contracts", "compliance"],
        "https://api.harvey.ai", "enterprise"),

    # ── Security ─────────────────────────────────────────────────────────
    "crowdstrike_ai": AIModel("crowdstrike_ai", "CrowdStrike Charlotte AI",
        "CrowdStrike", "security",
        ["cybersecurity", "threat_detection", "security"],
        "https://api.crowdstrike.com", "enterprise"),
    "darktrace": AIModel("darktrace", "Darktrace AI", "Darktrace", "security",
        ["cybersecurity", "threat_detection", "anomaly"],
        "https://api.darktrace.com", "enterprise"),

    # ── Robotics / physical AI ────────────────────────────────────────────
    "nvidia_isaac": AIModel("nvidia_isaac", "NVIDIA Isaac", "NVIDIA", "robotics",
        ["robotics", "manufacturing", "simulation", "autonomous"],
        "https://developer.nvidia.com/isaac", "enterprise"),
    "tesla_optimus": AIModel("tesla_optimus", "Tesla Optimus AI", "Tesla", "robotics",
        ["robotics", "autonomous", "manufacturing"],
        "https://tesla.com/optimus/api", "enterprise"),
    "figure_ai": AIModel("figure_ai", "Figure 01 AI", "Figure AI", "robotics",
        ["robotics", "autonomous", "manipulation"],
        "https://figure.ai/api", "enterprise"),

    # ── AI infrastructure ─────────────────────────────────────────────────
    "nvidia_dgx": AIModel("nvidia_dgx", "NVIDIA DGX Cloud", "NVIDIA", "infrastructure",
        ["infrastructure", "training", "deployment"],
        "https://api.nvidia.com/v1", "enterprise"),
    "aws_bedrock": AIModel("aws_bedrock", "AWS Bedrock", "Amazon", "infrastructure",
        ["infrastructure", "llm", "deployment"],
        "https://bedrock.us-east-1.amazonaws.com", "medium"),
    "azure_ai": AIModel("azure_ai", "Azure AI", "Microsoft", "infrastructure",
        ["infrastructure", "llm", "deployment", "security"],
        "https://management.azure.com", "medium"),
    "google_vertex": AIModel("google_vertex", "Google Vertex AI", "Google", "infrastructure",
        ["infrastructure", "llm", "deployment", "analytics"],
        "https://us-central1-aiplatform.googleapis.com", "medium"),
    "coreweave": AIModel("coreweave", "CoreWeave AI Cloud", "CoreWeave", "infrastructure",
        ["infrastructure", "training", "deployment"],
        "https://api.coreweave.com", "enterprise"),
    "huggingface": AIModel("huggingface", "Hugging Face Hub", "Hugging Face", "infrastructure",
        ["open_source", "deployment", "research", "models"],
        "https://api-inference.huggingface.co", "free", is_open_source=True),

    # ── Companions / conversational ───────────────────────────────────────
    "character_ai": AIModel("character_ai", "Character.AI", "Character.AI", "companion",
        ["companion", "entertainment", "gaming", "conversation"],
        "https://beta.character.ai/api", "free"),
    "replika": AIModel("replika", "Replika", "Luka", "companion",
        ["companion", "wellness", "mental_health"],
        "https://api.replika.ai", "low"),
    "pi_ai": AIModel("pi_ai", "Pi AI", "Inflection AI", "companion",
        ["companion", "assistant", "conversation"],
        "https://api.inflection.ai", "free"),

    # ── Simulation / science ──────────────────────────────────────────────
    "alphafold": AIModel("alphafold", "AlphaFold 3", "Google DeepMind", "science",
        ["science", "biology", "simulation", "research"],
        "https://alphafoldserver.com/api", "free", is_open_source=True),
    "nvidia_omniverse": AIModel("nvidia_omniverse", "NVIDIA Omniverse", "NVIDIA", "simulation",
        ["simulation", "engineering", "design", "digital_twin"],
        "https://api.nvidia.com/omniverse", "enterprise"),
    "wolfram_ai": AIModel("wolfram_ai", "Wolfram Alpha AI", "Wolfram Research", "science",
        ["math", "science", "problem_solving", "research"],
        "https://api.wolframalpha.com/v2/query", "low"),

    # ── Emerging / specialized ─────────────────────────────────────────────
    "deepl": AIModel("deepl", "DeepL", "DeepL", "translation",
        ["translation", "localization", "language"],
        "https://api-free.deepl.com/v2/translate", "low"),
    "khanmigo": AIModel("khanmigo", "Khanmigo", "Khan Academy", "education",
        ["education", "tutoring", "children", "learning"],
        "https://www.khanacademy.org/api", "free"),
    "duolingo_max": AIModel("duolingo_max", "Duolingo Max", "Duolingo", "education",
        ["language", "education", "learning"],
        "https://api.duolingo.com", "low"),
    "descript": AIModel("descript", "Descript", "Descript", "media",
        ["video", "podcast", "editing", "transcription"],
        "https://api.descript.com/v1", "medium"),
    "adcreative_ai": AIModel("adcreative_ai", "AdCreative.ai", "AdCreative.ai", "marketing",
        ["advertising", "creative", "marketing"],
        "https://api.adcreative.ai/v1", "medium"),
    "looka": AIModel("looka", "Looka", "Looka", "design",
        ["branding", "logo", "design"],
        "https://api.looka.com", "low"),
    "inworld": AIModel("inworld", "Inworld AI", "Inworld AI", "gaming",
        ["gaming", "npc", "vr", "ar"],
        "https://api.inworld.ai/v1", "medium"),
    "woebot": AIModel("woebot", "Woebot", "Woebot Health", "wellness",
        ["mental_health", "wellness", "coaching"],
        "https://api.woebot.io", "low"),
    "palantir_aip": AIModel("palantir_aip", "Palantir AIP", "Palantir", "analytics",
        ["defense", "analytics", "decision", "disaster"],
        "https://api.palantir.com", "enterprise"),
    "ibm_watson": AIModel("ibm_watson", "IBM Watson", "IBM", "llm",
        ["healthcare", "manufacturing", "analytics", "telecom", "finance"],
        "https://api.us-south.assistant.watson.cloud.ibm.com", "enterprise"),
    "stripe_radar": AIModel("stripe_radar", "Stripe Radar", "Stripe", "security",
        ["fraud_detection", "banking", "payments"],
        "https://api.stripe.com/v1", "medium"),
    "h2o_ai": AIModel("h2o_ai", "H2O.ai", "H2O.ai", "analytics",
        ["prediction", "analytics", "machine_learning"],
        "https://docs.h2o.ai/h2o/latest-stable/h2o-docs/rest-api", "medium",
        is_open_source=True),
    "aws_sagemaker": AIModel("aws_sagemaker", "AWS SageMaker", "Amazon", "infrastructure",
        ["prediction", "training", "deployment", "analytics"],
        "https://runtime.sagemaker.amazonaws.com", "medium"),
}
