"""
Professional Video Editing Bot — Main Entry Point

An AI-powered professional video editing and post-production studio for the DreamCobots ecosystem.

Core capabilities:
  • Project Management    — Create and manage video editing projects
  • Clip Management       — Add, trim, and arrange video clips (FREE: 5 clips max)
  • AI Transitions        — Smart scene transitions generated by AI (PRO+)
  • Color Grading         — Professional color grading with cinematic LUTs (PRO+)
  • Motion Tracking       — AI-powered object and face tracking (PRO+)
  • Render Optimization   — GPU-accelerated render pipeline optimization (ENTERPRISE)
  • NLE Export            — Export to Premiere Pro, Final Cut Pro, DaVinci Resolve (ENTERPRISE)

Tier limits:
  - FREE:       3 projects/month, 5 clips max, 1080p MP4 export.
  - PRO:        30 projects/month, unlimited clips, AI transitions, color grading, 4K export.
  - ENTERPRISE: Unlimited, render optimization, NLE compatibility, commercial rights.

Usage
-----
    from bots.professional_video_editing_bot import ProfessionalVideoEditingBot, Tier
    bot = ProfessionalVideoEditingBot(tier=Tier.PRO)
    project = bot.load_project()
    bot.add_clip("https://assets.example.com/clip01.mp4")
    print(bot.get_studio_dashboard())
"""

from __future__ import annotations

import sys
import os
import uuid
import random
from datetime import datetime

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ai-models-integration"))
from tiers import Tier, get_tier_config, get_upgrade_path  # noqa: F401
from bots.professional_video_editing_bot.tiers import (
    BOT_FEATURES,
    get_bot_tier_info,
    DAILY_LIMITS,
    CLIP_LIMITS,
    FEATURE_BASIC_EDITING,
    FEATURE_MP4_1080P_EXPORT,
    FEATURE_AI_TRANSITIONS,
    FEATURE_COLOR_GRADING,
    FEATURE_MOTION_TRACKING,
    FEATURE_EXPORT_4K,
    FEATURE_RENDER_OPTIMIZATION,
    FEATURE_NLE_COMPATIBILITY,
)

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from framework import GlobalAISourcesFlow  # noqa: F401

_COLOR_PRESETS = {
    "cinematic": {"contrast": 1.15, "saturation": 0.85, "shadows": -10, "highlights": -5, "temperature": -200},
    "warm_glow": {"contrast": 1.05, "saturation": 1.10, "shadows": 5, "highlights": 0, "temperature": 300},
    "cool_blue": {"contrast": 1.08, "saturation": 0.90, "shadows": -5, "highlights": 3, "temperature": -350},
    "vintage": {"contrast": 0.90, "saturation": 0.75, "shadows": 8, "highlights": -8, "temperature": 150},
    "high_contrast": {"contrast": 1.30, "saturation": 1.05, "shadows": -15, "highlights": -10, "temperature": 0},
    "black_white": {"contrast": 1.20, "saturation": 0.0, "shadows": -5, "highlights": -3, "temperature": 0},
}


class ProfessionalVideoEditingBotError(Exception):
    """Raised when a monthly limit, clip limit, or feature restriction is violated."""


class ProfessionalVideoEditingBot:
    """AI-powered professional video editing bot with tier-based feature gating.

    Parameters
    ----------
    tier : Tier
        Subscription tier controlling monthly limits, clip limits, and feature access.
    """

    def __init__(self, tier: Tier = Tier.FREE) -> None:
        self.tier = tier
        self.config = get_tier_config(tier)
        self.tier_info = get_bot_tier_info(tier)
        self.flow = GlobalAISourcesFlow(bot_name="ProfessionalVideoEditingBot")
        self._monthly_count: int = 0
        self._projects: dict[str, dict] = {}
        self._active_project_id: str | None = None

    def _check_monthly_limit(self) -> None:
        """Raise ProfessionalVideoEditingBotError if the monthly project limit is exceeded."""
        limit = DAILY_LIMITS[self.tier.value]
        if limit is not None and self._monthly_count >= limit:
            upgrade = get_upgrade_path(self.tier)
            upgrade_msg = (
                f" Upgrade to {upgrade.name} (${upgrade.price_usd_monthly}/mo) for more."
                if upgrade else ""
            )
            raise ProfessionalVideoEditingBotError(
                f"Monthly project limit of {limit} reached for the "
                f"{self.tier.value.upper()} tier.{upgrade_msg}"
            )

    def _check_feature(self, feature: str) -> None:
        """Raise ProfessionalVideoEditingBotError if the feature is not available on the current tier."""
        if feature not in BOT_FEATURES[self.tier.value]:
            upgrade = get_upgrade_path(self.tier)
            upgrade_msg = (
                f" Upgrade to {upgrade.name} for access." if upgrade else ""
            )
            raise ProfessionalVideoEditingBotError(
                f"Feature '{feature}' is not available on the {self.tier.value.upper()} tier.{upgrade_msg}"
            )

    def _record(self) -> None:
        self._monthly_count += 1

    def load_project(self, project_id: str | None = None) -> dict:
        """Load an existing video project or create a new one.

        Parameters
        ----------
        project_id : str | None
            Existing project ID to load, or None to create a fresh project.
        """
        self._check_feature(FEATURE_BASIC_EDITING)
        result = self.flow.run_pipeline(
            raw_data={"task": "load_project", "project_id": project_id},
            learning_method="unsupervised",
        )
        if project_id and project_id in self._projects:
            project = self._projects[project_id]
            status = "loaded"
        else:
            project_id = project_id or f"vproj_{uuid.uuid4().hex[:10]}"
            total_dur = 0.0
            project = {
                "project_id": project_id,
                "name": f"Video Project {len(self._projects) + 1}",
                "clips": [],
                "timeline_duration_sec": total_dur,
                "resolution": "1920x1080",
                "fps": 30,
                "created_at": datetime.utcnow().isoformat() + "Z",
            }
            self._projects[project_id] = project
            self._active_project_id = project_id
            self._record()
            status = "created"
        self._active_project_id = project_id
        return {
            "project_id": project_id,
            "name": project["name"],
            "clips": project["clips"],
            "clip_count": len(project["clips"]),
            "timeline_duration_sec": project.get("timeline_duration_sec", 0.0),
            "resolution": project.get("resolution", "1920x1080"),
            "fps": project.get("fps", 30),
            "created_at": project["created_at"],
            "status": status,
            "framework_pipeline": result.get("bot_name"),
        }

    def add_clip(self, clip_source: str, position_sec: float = 0.0) -> dict:
        """Add a video clip to the active project (clip count limits apply on FREE tier).

        Parameters
        ----------
        clip_source : str
            URL or file path of the video clip to add.
        position_sec : float
            Timeline position in seconds where the clip is inserted.
        """
        self._check_feature(FEATURE_BASIC_EDITING)
        project_id = self._active_project_id or f"vproj_{uuid.uuid4().hex[:10]}"
        if project_id not in self._projects:
            self._projects[project_id] = {
                "project_id": project_id, "name": "Auto Project", "clips": [],
                "timeline_duration_sec": 0.0, "resolution": "1920x1080",
                "fps": 30, "created_at": datetime.utcnow().isoformat() + "Z",
            }
            self._active_project_id = project_id

        project = self._projects[project_id]
        clip_limit = CLIP_LIMITS[self.tier.value]
        current_clips = len(project["clips"])
        if clip_limit is not None and current_clips >= clip_limit:
            upgrade = get_upgrade_path(self.tier)
            upgrade_msg = f" Upgrade to {upgrade.name} for unlimited clips." if upgrade else ""
            raise ProfessionalVideoEditingBotError(
                f"Clip limit of {clip_limit} reached for the {self.tier.value.upper()} tier.{upgrade_msg}"
            )
        result = self.flow.run_pipeline(
            raw_data={"task": "add_clip", "clip_source": clip_source, "position_sec": position_sec},
            learning_method="supervised",
        )
        clip_id = f"clip_{uuid.uuid4().hex[:8]}"
        duration = round(random.uniform(3.0, 30.0), 2)
        clip = {"clip_id": clip_id, "clip_source": clip_source, "position_sec": position_sec, "duration_sec": duration}
        project["clips"].append(clip)
        project["timeline_duration_sec"] = round(position_sec + duration, 2)
        return {
            "clip_id": clip_id,
            "clip_source": clip_source,
            "position_sec": position_sec,
            "duration_sec": duration,
            "resolution": "1920x1080",
            "fps": 30,
            "project_id": project_id,
            "clip_number": len(project["clips"]),
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "framework_pipeline": result.get("bot_name"),
        }

    def apply_transition(self, clip_id_a: str, clip_id_b: str, transition: str) -> dict:
        """Apply an AI-powered transition between two clips (PRO+).

        Parameters
        ----------
        clip_id_a : str
            Source clip ID.
        clip_id_b : str
            Target clip ID.
        transition : str
            Transition type: dissolve, wipe, zoom, spin, morph, fade.
        """
        self._check_feature(FEATURE_AI_TRANSITIONS)
        result = self.flow.run_pipeline(
            raw_data={"task": "apply_transition", "clip_id_a": clip_id_a, "clip_id_b": clip_id_b, "transition": transition},
            learning_method="supervised",
        )
        return {
            "clip_id_a": clip_id_a,
            "clip_id_b": clip_id_b,
            "transition": transition,
            "duration_sec": 1.0,
            "ai_optimized": True,
            "easing": "ease-in-out",
            "status": "applied",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "framework_pipeline": result.get("bot_name"),
        }

    def apply_color_grade(self, clip_id: str, preset: str) -> dict:
        """Apply a color grading preset to a clip (PRO+).

        Parameters
        ----------
        clip_id : str
            The clip to color grade.
        preset : str
            Color preset: cinematic, warm_glow, cool_blue, vintage, high_contrast, black_white.
        """
        self._check_feature(FEATURE_COLOR_GRADING)
        adjustments = _COLOR_PRESETS.get(preset, _COLOR_PRESETS["cinematic"])
        result = self.flow.run_pipeline(
            raw_data={"task": "apply_color_grade", "clip_id": clip_id, "preset": preset},
            learning_method="supervised",
        )
        return {
            "clip_id": clip_id,
            "preset": preset,
            "lut_applied": f"{preset}.cube",
            "color_adjustments": adjustments,
            "status": "applied",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "framework_pipeline": result.get("bot_name"),
        }

    def apply_motion_tracking(self, clip_id: str, target: str) -> dict:
        """Apply AI motion tracking to a subject in a clip (PRO+).

        Parameters
        ----------
        clip_id : str
            The clip to perform motion tracking on.
        target : str
            Description of the tracking target (e.g. 'face', 'car', 'logo').
        """
        self._check_feature(FEATURE_MOTION_TRACKING)
        result = self.flow.run_pipeline(
            raw_data={"task": "apply_motion_tracking", "clip_id": clip_id, "target": target},
            learning_method="supervised",
        )
        uid = uuid.uuid4().hex[:12]
        return {
            "clip_id": clip_id,
            "target": target,
            "tracking_points": random.randint(12, 48),
            "confidence": round(random.uniform(0.88, 0.99), 2),
            "track_data_url": f"https://cdn.dreamcobots.ai/tracking/{uid}.json",
            "frames_analyzed": random.randint(150, 900),
            "status": "tracked",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "framework_pipeline": result.get("bot_name"),
        }

    def optimize_render(self, project_id: str) -> dict:
        """Optimize the render pipeline for a project using GPU acceleration (ENTERPRISE only).

        Parameters
        ----------
        project_id : str
            The project to optimize.
        """
        self._check_feature(FEATURE_RENDER_OPTIMIZATION)
        result = self.flow.run_pipeline(
            raw_data={"task": "optimize_render", "project_id": project_id},
            learning_method="self_supervised",
        )
        original_time = round(random.uniform(15.0, 60.0), 1)
        speedup = round(random.uniform(3.5, 8.0), 1)
        return {
            "project_id": project_id,
            "original_render_time_min": original_time,
            "optimized_render_time_min": round(original_time / speedup, 1),
            "speedup_factor": speedup,
            "gpu_acceleration": True,
            "optimizations_applied": [
                "Multi-GPU parallel processing",
                "Smart proxy rendering for 4K clips",
                "Background caching of color grading LUTs",
                "Hardware H.265/HEVC encoding",
            ],
            "status": "optimized",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "framework_pipeline": result.get("bot_name"),
        }

    def export_project(
        self, project_id: str, format: str = "MP4", nle_compatible: str | None = None
    ) -> dict:
        """Export the video project to a media file.

        FREE: 1080p MP4. PRO: 4K export. ENTERPRISE: NLE-compatible project files.

        Parameters
        ----------
        project_id : str
            Project to export.
        format : str
            Output format: MP4, MOV, MXF.
        nle_compatible : str | None
            NLE software name for project export (e.g. 'Premiere Pro'). ENTERPRISE only.
        """
        is_4k = FEATURE_EXPORT_4K in BOT_FEATURES[self.tier.value]
        if nle_compatible:
            self._check_feature(FEATURE_NLE_COMPATIBILITY)
        elif is_4k:
            self._check_feature(FEATURE_EXPORT_4K)
        else:
            self._check_feature(FEATURE_MP4_1080P_EXPORT)
        result = self.flow.run_pipeline(
            raw_data={"task": "export_project", "project_id": project_id, "format": format, "nle": nle_compatible},
            learning_method="supervised",
        )
        uid = uuid.uuid4().hex[:12]
        resolution = "3840x2160" if is_4k else "1920x1080"
        project = self._projects.get(project_id, {})
        duration = project.get("timeline_duration_sec", random.uniform(30, 300))
        bitrate_mbps = 50 if is_4k else 16
        size_gb = round(duration * bitrate_mbps / 8 / 1024, 2)
        return {
            "project_id": project_id,
            "format": format.upper(),
            "resolution": resolution,
            "fps": 30,
            "duration_sec": round(duration, 1),
            "file_url": f"https://cdn.dreamcobots.ai/exports/{uid}.{format.lower()}",
            "file_size_gb": size_gb,
            "nle_compatible": nle_compatible,
            "color_space": "Rec. 709" if not is_4k else "Rec. 2020",
            "status": "exported",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "framework_pipeline": result.get("bot_name"),
        }

    def get_studio_dashboard(self) -> dict:
        """Return studio dashboard with monthly usage stats and tier information."""
        limit = DAILY_LIMITS[self.tier.value]
        clip_limit = CLIP_LIMITS[self.tier.value]
        upgrade = get_upgrade_path(self.tier)
        return {
            "bot_name": "ProfessionalVideoEditingBot",
            "tier": self.tier.value,
            "tier_display": self.config.name,
            "price_usd_monthly": self.config.price_usd_monthly,
            "monthly_limit": limit,
            "monthly_count": self._monthly_count,
            "remaining": (limit - self._monthly_count) if limit is not None else "unlimited",
            "clip_limit": clip_limit if clip_limit is not None else "unlimited",
            "projects_open": len(self._projects),
            "active_project_id": self._active_project_id,
            "features": BOT_FEATURES[self.tier.value],
            "commercial_rights": self.tier_info["commercial_rights"],
            "upgrade_available": upgrade is not None,
            "upgrade_to": upgrade.name if upgrade else None,
            "upgrade_price_usd": upgrade.price_usd_monthly if upgrade else None,
        }
