"""
Cost Justification Engine — Autonomous cost explanation and payment options.

Every DreamCo bot that may incur costs must be able to:
1. Describe the cost in plain language.
2. Explain WHY the cost is worth it (ROI justification).
3. Present available payment options (tokens, subscriptions, one-time).
4. Autonomously select the most cost-effective payment path.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from framework import GlobalAISourcesFlow  # noqa: F401

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class CostItem:
    """A single line-item cost."""

    name: str
    amount_usd: float
    frequency: str  # 'one-time' | 'monthly' | 'annual' | 'per-request'
    description: str
    is_optional: bool = False


@dataclass
class PaymentOption:
    """One of the available ways to pay for a DreamCo feature."""

    option_id: str
    label: str
    amount_usd: float
    currency: str = "USD"
    method: str = "card"  # 'card' | 'paypal' | 'tokens' | 'crypto'
    savings_vs_monthly: float = 0.0
    description: str = ""


@dataclass
class CostJustification:
    """
    Full cost justification report returned to the user / operator.

    Attributes
    ----------
    total_monthly_usd : float
        Total estimated monthly cost.
    total_annual_usd  : float
        Total estimated annual cost (with any annual discount applied).
    roi_explanation   : str
        Plain-language explanation of the value delivered.
    break_even_months : float
        Approximate months to break even based on estimated savings.
    payment_options   : list[PaymentOption]
        Available ways to pay.
    recommended_option: str
        option_id of the recommended payment option.
    line_items        : list[CostItem]
        Detailed cost breakdown.
    autonomous_decision: str
        The bot's autonomous recommendation (e.g. 'proceed', 'defer', 'escalate').
    """

    total_monthly_usd: float
    total_annual_usd: float
    roi_explanation: str
    break_even_months: float
    payment_options: list[PaymentOption]
    recommended_option: str
    line_items: list[CostItem]
    autonomous_decision: str
    token_cost: Optional[int] = None  # tokens required (if token billing)
    token_balance: Optional[int] = None  # current token balance


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


class CostJustificationEngine:
    """
    Builds cost justification reports and autonomously decides whether to
    proceed with an upgrade or feature purchase.

    Parameters
    ----------
    token_balance : int
        Current token balance of the DreamCo account.
    tokens_per_dollar : float
        How many tokens equal one USD (default 100).
    """

    # Annual discount applied to yearly subscriptions
    ANNUAL_DISCOUNT: float = 0.20  # 20% off

    # Token markup (clients bear the cost via token consumption)
    TOKEN_MARKUP: float = 1.15  # 15% markup on token purchases

    def __init__(
        self,
        token_balance: int = 0,
        tokens_per_dollar: float = 100.0,
    ) -> None:
        self.token_balance = token_balance
        self.tokens_per_dollar = tokens_per_dollar

    # ── Public API ────────────────────────────────────────────────────────────

    def justify(
        self,
        feature_name: str,
        monthly_cost_usd: float,
        estimated_monthly_savings_usd: float,
        line_items: Optional[list[CostItem]] = None,
        include_tokens: bool = True,
    ) -> CostJustification:
        """
        Build a full cost justification for *feature_name*.

        Parameters
        ----------
        feature_name : str
            Human-readable name of the feature or upgrade.
        monthly_cost_usd : float
            Monthly fee in USD.
        estimated_monthly_savings_usd : float
            Estimated monthly savings / revenue generated by the feature.
        line_items : list[CostItem] | None
            Optional detailed cost breakdown.
        include_tokens : bool
            Whether to include a token-based payment option.

        Returns
        -------
        CostJustification
        """
        annual_usd = round(monthly_cost_usd * 12 * (1 - self.ANNUAL_DISCOUNT), 2)
        token_cost = int(monthly_cost_usd * self.tokens_per_dollar * self.TOKEN_MARKUP)

        # Build payment options
        options: list[PaymentOption] = [
            PaymentOption(
                option_id="monthly_card",
                label="Monthly — Credit / Debit Card",
                amount_usd=monthly_cost_usd,
                method="card",
                description=f"${monthly_cost_usd:.2f}/month billed to your card.",
            ),
            PaymentOption(
                option_id="monthly_paypal",
                label="Monthly — PayPal",
                amount_usd=monthly_cost_usd,
                method="paypal",
                description=f"${monthly_cost_usd:.2f}/month via PayPal.",
            ),
            PaymentOption(
                option_id="annual_card",
                label=f"Annual — Credit Card ({int(self.ANNUAL_DISCOUNT * 100)}% off)",
                amount_usd=annual_usd,
                method="card",
                savings_vs_monthly=round(monthly_cost_usd * 12 - annual_usd, 2),
                description=(
                    f"${annual_usd:.2f}/year (saves "
                    f"${monthly_cost_usd * 12 - annual_usd:.2f} vs monthly)."
                ),
            ),
        ]
        if include_tokens:
            options.append(
                PaymentOption(
                    option_id="tokens",
                    label="DreamCo Tokens",
                    amount_usd=monthly_cost_usd * self.TOKEN_MARKUP,
                    currency="TOKENS",
                    method="tokens",
                    description=(
                        f"{token_cost:,} tokens required "
                        f"(balance: {self.token_balance:,} tokens)."
                    ),
                )
            )

        # Recommended option
        has_enough_tokens = self.token_balance >= token_cost
        if has_enough_tokens and include_tokens:
            recommended = "tokens"
        elif annual_usd < monthly_cost_usd * 12:
            recommended = "annual_card"
        else:
            recommended = "monthly_card"

        # ROI explanation
        net_monthly = estimated_monthly_savings_usd - monthly_cost_usd
        break_even = (
            monthly_cost_usd / estimated_monthly_savings_usd
            if estimated_monthly_savings_usd > 0
            else float("inf")
        )
        roi_pct = (
            (estimated_monthly_savings_usd / monthly_cost_usd - 1) * 100
            if monthly_cost_usd > 0
            else 0
        )
        roi_explanation = (
            f"'{feature_name}' costs ${monthly_cost_usd:.2f}/month and is projected to "
            f"generate or save ${estimated_monthly_savings_usd:.2f}/month — "
            f"a net gain of ${net_monthly:.2f}/month ({roi_pct:.0f}% ROI). "
            f"Break-even in ~{break_even:.1f} month(s). "
            "DreamCo bots work 24/7 with zero sick days or overtime, maximising value."
        )

        # Autonomous decision
        if estimated_monthly_savings_usd > monthly_cost_usd:
            autonomous_decision = "proceed"
        elif estimated_monthly_savings_usd > monthly_cost_usd * 0.7:
            autonomous_decision = "proceed_with_caution"
        else:
            autonomous_decision = "defer_to_operator"

        return CostJustification(
            total_monthly_usd=monthly_cost_usd,
            total_annual_usd=annual_usd,
            roi_explanation=roi_explanation,
            break_even_months=round(break_even, 2),
            payment_options=options,
            recommended_option=recommended,
            line_items=line_items or [],
            autonomous_decision=autonomous_decision,
            token_cost=token_cost,
            token_balance=self.token_balance,
        )

    def add_tokens(self, amount: int) -> int:
        """Add *amount* tokens to the balance and return the new balance."""
        self.token_balance += amount
        return self.token_balance

    def deduct_tokens(self, amount: int) -> dict:
        """
        Deduct *amount* tokens.  Returns a dict with 'success' and 'balance'.
        """
        if self.token_balance < amount:
            return {
                "success": False,
                "balance": self.token_balance,
                "error": f"Insufficient tokens: need {amount:,}, have {self.token_balance:,}.",
            }
        self.token_balance -= amount
        return {"success": True, "balance": self.token_balance}

    def format_report(self, justification: CostJustification) -> str:
        """Return a human-readable text report of the justification."""
        lines = [
            "=" * 60,
            "DreamCo Cost Justification Report",
            "=" * 60,
            justification.roi_explanation,
            "",
            f"Monthly cost   : ${justification.total_monthly_usd:>10.2f}",
            f"Annual cost    : ${justification.total_annual_usd:>10.2f}",
            f"Break-even     : {justification.break_even_months:>10.2f} month(s)",
            f"Bot decision   : {justification.autonomous_decision}",
            "",
            "Payment Options:",
        ]
        for opt in justification.payment_options:
            lines.append(f"  [{opt.option_id}] {opt.label}: {opt.description}")
        lines.append(f"\nRecommended: {justification.recommended_option}")
        if justification.token_cost is not None:
            lines.append(
                f"Token cost: {justification.token_cost:,} tokens  "
                f"(balance: {justification.token_balance:,})"
            )
        lines.append("=" * 60)
        return "\n".join(lines)


__all__ = [
    "CostJustificationEngine",
    "CostItem",
    "PaymentOption",
    "CostJustification",
]
