"""Compliance packages with real requirements for all supported industries."""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from core.compliance import CompliancePackage

PRICING_TIERS = {
    "Starter": {
        "price": "$499",
        "description": "Essential compliance tools for solo operators",
    },
    "Professional": {
        "price": "$1,499",
        "description": "Full compliance suite for small teams",
    },
    "Enterprise": {
        "price": "$4,999",
        "description": "Complete enterprise compliance platform",
    },
    "Master": {
        "price": "$9,999",
        "description": "White-label compliance solution for agencies",
    },
}


def get_all_packages():
    """Return all compliance packages for DreamCobots."""
    packages = [
        CompliancePackage(
            name="Medical Compliance Suite",
            category="MEDICAL",
            requirements=[
                "HIPAA Privacy Rule implementation",
                "HIPAA Security Rule technical safeguards",
                "HITECH Act compliance",
                "Business Associate Agreements (BAAs) management",
                "PHI access controls and audit logs",
                "Breach notification procedures (60-day HHS reporting)",
                "Annual security risk assessment",
                "Staff HIPAA training (annual)",
                "Minimum necessary standard enforcement",
                "Patient right to access and amendment",
            ],
            checklist=[
                "Designate HIPAA Privacy Officer",
                "Designate HIPAA Security Officer",
                "Conduct annual risk analysis",
                "Implement workforce training program",
                "Execute BAAs with all business associates",
                "Establish breach notification process",
                "Create policies for PHI use and disclosure",
                "Implement technical access controls",
                "Enable audit logging on all PHI systems",
                "Test incident response plan annually",
            ],
            certifications=[
                "HIPAA Compliance Certificate",
                "HITECH Attestation",
                "SOC 2 Type II (recommended)",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Legal Compliance Suite",
            category="LEGAL",
            requirements=[
                "State bar compliance (if providing legal services)",
                "Unauthorized practice of law (UPL) prevention",
                "Client confidentiality and privilege protection",
                "Conflict of interest management",
                "Document retention policies (7 years+)",
                "Trust account management (IOLTA)",
                "Fee agreement documentation",
                "E-discovery readiness",
                "Malpractice insurance documentation",
                "ABA Model Rules compliance",
            ],
            checklist=[
                "Review ABA Model Rules of Professional Conduct",
                "Implement conflict check system",
                "Establish client file retention policy",
                "Set up IOLTA trust accounting",
                "Secure client portal with encryption",
                "Annual continuing legal education (CLE) tracking",
                "Implement client intake and engagement letters",
                "Maintain malpractice insurance",
                "Document fee arrangements in writing",
                "Regular ethics compliance training",
            ],
            certifications=[
                "State Bar Good Standing",
                "ABA Compliance Attestation",
                "Malpractice Insurance Certificate",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Financial Compliance Suite",
            category="FINANCIAL",
            requirements=[
                "SEC/FINRA registration (if applicable)",
                "Anti-Money Laundering (AML) procedures",
                "Know Your Customer (KYC) verification",
                "Bank Secrecy Act (BSA) compliance",
                "Sarbanes-Oxley (SOX) compliance (public companies)",
                "Consumer Financial Protection Bureau (CFPB) regulations",
                "PCI DSS compliance for payment processing",
                "GLBA (Gramm-Leach-Bliley Act) safeguards",
                "FinCEN Beneficial Ownership reporting (2024)",
                "State money transmitter licenses",
            ],
            checklist=[
                "Register with FinCEN if required",
                "Implement AML/KYC program",
                "Appoint BSA/AML Compliance Officer",
                "Conduct customer due diligence (CDD)",
                "File SARs for suspicious activity",
                "Maintain 5-year transaction records",
                "Annual AML training for staff",
                "Submit Beneficial Ownership report by Jan 1, 2025",
                "PCI DSS SAQ completion",
                "Annual compliance audit",
            ],
            certifications=[
                "SEC Registration (if applicable)",
                "PCI DSS Certificate",
                "CAMS Certification (AML)",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Cybersecurity Compliance Suite",
            category="CYBERSECURITY",
            requirements=[
                "NIST Cybersecurity Framework implementation",
                "SOC 2 Type II audit",
                "ISO 27001 alignment",
                "GDPR/CCPA compliance",
                "Penetration testing (annual)",
                "Vulnerability management program",
                "Incident response plan",
                "Security awareness training (annual)",
                "Multi-factor authentication (MFA) enforcement",
                "Data classification and handling policy",
            ],
            checklist=[
                "Complete NIST CSF assessment",
                "Implement MFA for all users",
                "Deploy endpoint detection and response (EDR)",
                "Enable audit logging on all systems",
                "Conduct annual penetration test",
                "Implement patch management process (30-day SLA)",
                "Conduct phishing simulation (quarterly)",
                "Document and test incident response plan",
                "Implement data loss prevention (DLP)",
                "Vendor security assessment program",
            ],
            certifications=[
                "SOC 2 Type II",
                "ISO 27001",
                "CISA/CISSP (staff certifications)",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Education Compliance Suite",
            category="EDUCATION",
            requirements=[
                "FERPA (Family Educational Rights and Privacy Act)",
                "COPPA compliance for under-13 users",
                "ADA Section 508 accessibility",
                "State education department licensing",
                "Accreditation body requirements",
                "Title IX compliance",
                "Student data privacy laws (state-specific)",
                "Online education FTC guidelines",
                "Copyright and DMCA compliance",
                "Background checks for staff",
            ],
            checklist=[
                "Implement FERPA data protection policies",
                "Establish student records access procedures",
                "COPPA parental consent mechanisms",
                "Accessibility audit (WCAG 2.1 AA)",
                "Title IX coordinator designation",
                "Annual staff training on student privacy",
                "DMCA takedown process established",
                "Background check policy for all staff",
                "State-specific licensing compliance",
                "Annual compliance review",
            ],
            certifications=[
                "State Education License",
                "Accreditation (regional/national)",
                "FERPA Compliance Attestation",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Funeral Industry Compliance Suite",
            category="FUNERAL",
            requirements=[
                "FTC Funeral Rule compliance (16 CFR 453)",
                "State funeral director licensing",
                "State funeral establishment license",
                "Embalmer licensing (if applicable)",
                "OSHA bloodborne pathogens standard",
                "State board of funeral service regulations",
                "Pre-need funeral contract regulations",
                "Crematory licensing (if applicable)",
                "Death certificate requirements",
                "Transport and disposition permits",
            ],
            checklist=[
                "Obtain and maintain funeral director license",
                "Post General Price List (GPL) conspicuously",
                "Provide itemized price list to all clients",
                "No required packages without choice",
                "Embalming disclosure (not always required)",
                "Pre-need contract escrow requirements",
                "OSHA safety training and PPE",
                "Annual state board continuing education",
                "Cremation authorization procedures",
                "Transport and disposition record keeping",
            ],
            certifications=[
                "State Funeral Director License",
                "NFDA Member (recommended)",
                "Green Burial Council (optional)",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Human Resources Compliance Suite",
            category="HR",
            requirements=[
                "EEOC Equal Employment Opportunity compliance",
                "FLSA wage and hour compliance",
                "FMLA leave requirements (50+ employees)",
                "ADA reasonable accommodation",
                "OSHA workplace safety",
                "I-9 employment eligibility verification",
                "Title VII anti-discrimination",
                "ADEA age discrimination (40+ employees)",
                "State-specific employment laws",
                "Affordable Care Act (ACA) compliance (50+ employees)",
            ],
            checklist=[
                "Post required EEOC/FMLA/OSHA notices",
                "File EEO-1 report annually (100+ employees)",
                "I-9 verification for all new hires",
                "Classify employees correctly (exempt/non-exempt)",
                "Track and pay overtime correctly",
                "Develop and distribute employee handbook",
                "Annual harassment prevention training",
                "ADA interactive process for accommodations",
                "State-required leave law compliance",
                "Annual HR policy review",
            ],
            certifications=[
                "SHRM-CP or SHRM-SCP (staff)",
                "PHR/SPHR Certification",
                "OSHA 30-Hour Training",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Marketing Compliance Suite",
            category="MARKETING",
            requirements=[
                "CAN-SPAM Act email marketing compliance",
                "GDPR email consent (EU audiences)",
                "CCPA privacy rights (California)",
                "FTC endorsement and testimonial guidelines",
                "TCPA compliance for SMS marketing",
                "Truth in Advertising standards",
                "Social media platform terms of service",
                "Cookie consent and privacy policy",
                "Influencer marketing disclosure requirements",
                "Children's Advertising Review Unit (CARU) if targeting minors",
            ],
            checklist=[
                "CAN-SPAM opt-out mechanism in all emails",
                "GDPR-compliant consent forms",
                "Privacy policy updated for CCPA",
                "FTC disclosure on all paid promotions (#ad #sponsored)",
                "TCPA opt-in for SMS campaigns",
                "Substantiate all marketing claims",
                "Cookie banner and consent management",
                "Influencer contracts with disclosure requirements",
                "Platform-specific ad policy review",
                "Annual marketing compliance audit",
            ],
            certifications=[
                "DMA (Direct Marketing Association) Member",
                "IAB Privacy Certification",
                "Google Ads Certification",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="Real Estate Compliance Suite",
            category="REAL_ESTATE",
            requirements=[
                "State real estate broker/agent license",
                "NAR Code of Ethics compliance",
                "Fair Housing Act (FHA) compliance",
                "RESPA (Real Estate Settlement Procedures Act)",
                "Truth in Lending Act (TILA) compliance",
                "State-specific disclosure requirements",
                "Anti-Money Laundering (AML) for real estate",
                "FinCEN Geographic Targeting Orders (GTO)",
                "E&O Insurance maintenance",
                "MLS rules and regulations",
            ],
            checklist=[
                "Maintain current state license",
                "Complete NAR ethics training (every 3 years)",
                "Fair Housing training (annual)",
                "Required property disclosures for each transaction",
                "RESPA affiliated business disclosure",
                "AML Customer Due Diligence (CDD)",
                "FinCEN GTO compliance (if in covered areas)",
                "E&O insurance active",
                "Continuing education requirements met",
                "Transaction record retention (3-5 years by state)",
            ],
            certifications=[
                "State Real Estate License",
                "NAR Membership",
                "CRS/ABR/SRES Designations (optional)",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="E-Commerce Compliance Suite",
            category="ECOMMERCE",
            requirements=[
                "PCI DSS compliance for payment processing",
                "GDPR/CCPA data privacy",
                "ADA website accessibility (WCAG 2.1)",
                "FTC e-commerce disclosure rules",
                "Sales tax nexus and remittance (Wayfair decision)",
                "Product safety regulations (CPSC)",
                "Amazon/eBay/Shopify platform terms",
                "Import/export regulations (if applicable)",
                "Consumer protection laws (state-specific)",
                "Subscription billing compliance (negative option)",
            ],
            checklist=[
                "PCI DSS SAQ completion",
                "Privacy policy and cookie consent banner",
                "WCAG 2.1 AA accessibility audit",
                "All pricing transparent (no hidden fees)",
                "Sales tax collection in nexus states",
                "Return/refund policy clearly posted",
                "Product safety documentation",
                "FTC negative option disclosure (subscriptions)",
                "Secure checkout (SSL/TLS)",
                "Annual compliance review",
            ],
            certifications=[
                "PCI DSS Compliance Certificate",
                "ADA Compliance Audit Report",
                "BBB Accreditation (recommended)",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
        CompliancePackage(
            name="General Business Compliance Suite",
            category="GENERAL",
            requirements=[
                "Business registration with Secretary of State",
                "Federal EIN from IRS",
                "Local business license",
                "Zoning compliance",
                "Federal and state tax registration",
                "FinCEN Beneficial Ownership Report (2024)",
                "General liability insurance",
                "Workers compensation insurance (if employees)",
                "Industry-specific licenses",
                "Annual report filing",
            ],
            checklist=[
                "Register business entity (LLC/Corp)",
                "Obtain Federal EIN",
                "Open dedicated business bank account",
                "Register for state and local taxes",
                "File FinCEN BOI report by January 1, 2025",
                "Obtain required business licenses",
                "Secure general liability insurance",
                "Register trademarks/copyrights",
                "Set up accounting and bookkeeping",
                "Annual registered agent maintenance",
            ],
            certifications=[
                "Certificate of Incorporation/Organization",
                "EIN Letter from IRS",
                "Business License",
            ],
            pricing_tiers=PRICING_TIERS,
        ),
    ]
    return packages
