"""
Creator Economy Bot — tier-aware monetization assistant for content creators.

Usage
-----
    from bots.creator_economy.creator_economy_bot import CreatorEconomyBot
    from bots.ai_chatbot.tiers import Tier

    bot = CreatorEconomyBot(tier=Tier.PRO)
    response = bot.chat("Generate a brand sponsorship pitch for my YouTube channel")
    print(response["message"])
"""
# Adheres to the GLOBAL AI SOURCES FLOW framework — see framework/global_ai_sources_flow.py


import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'ai-models-integration'))

from tiers import Tier, get_tier_config, get_upgrade_path
from bots.creator_economy.tiers import (
    CE_EXTRA_FEATURES,
    CE_TOOLS,
    get_ce_tier_info,
)


class CreatorEconomyTierError(Exception):
    """Raised when a creator tool is not available on the current tier."""


class CreatorEconomyRequestLimitError(Exception):
    """Raised when the monthly request quota has been exhausted."""


class CreatorEconomyBot:
    """
    Tier-aware assistant for content creators and digital entrepreneurs.

    Supported tools (by tier):
      FREE       -- content ideas, hashtag generator, bio optimizer
      PRO        -- brand pitch deck, revenue dashboard, merch store setup
      ENTERPRISE -- talent agency integration, IP protection, multi-platform deals

    Parameters
    ----------
    tier : Tier
        Subscription tier controlling tool access.
    """

    def __init__(self, tier: Tier = Tier.FREE) -> None:
        self.tier = tier
        self.config = get_tier_config(tier)
        self._request_count: int = 0
        self._history: list[dict] = []

    # ------------------------------------------------------------------
    # Core chat interface
    # ------------------------------------------------------------------

    def chat(self, message: str, tool: str | None = None) -> dict:
        """
        Process a creator monetization request and return a structured response.

        Parameters
        ----------
        message : str
            The user's natural-language request.
        tool : str | None
            Optional tool to invoke directly.

        Returns
        -------
        dict with keys: ``message``, ``tool``, ``tier``,
        ``requests_used``, ``requests_remaining``.
        """
        self._check_request_limit()
        active_tool = tool or self._default_tool(message)
        self._check_tool_access(active_tool)

        self._request_count += 1
        response_text = (
            f"[CreatorEconomyBot/{active_tool}] Processed: {message!r}"
        )
        self._history.append({"role": "user", "content": message})
        self._history.append({"role": "assistant", "content": response_text})

        return {
            "message": response_text,
            "tool": active_tool,
            "tier": self.tier.value,
            "requests_used": self._request_count,
            "requests_remaining": self._requests_remaining(),
        }

    def generate_pitch(self, brand: str, platform: str) -> dict:
        """
        Generate a brand sponsorship pitch for a given brand and platform.

        Returns
        -------
        dict with keys: ``brand``, ``platform``, ``pitch``, ``tier``.
        """
        self._check_request_limit()
        self._check_tool_access("brand_pitch_generator")
        self._request_count += 1

        return {
            "brand": brand,
            "platform": platform,
            "pitch": (
                f"[Mock] Sponsorship pitch for {brand!r} on {platform!r} — "
                "generated by CreatorEconomyBot."
            ),
            "tier": self.tier.value,
        }

    def list_tools(self) -> list[str]:
        """Return the creator tools available on the current tier."""
        return list(CE_TOOLS.get(self.tier.value, []))

    def get_history(self) -> list[dict]:
        """Return a copy of the conversation history."""
        return list(self._history)

    def clear_history(self) -> None:
        """Clear conversation history."""
        self._history = []

    # ------------------------------------------------------------------
    # Tier information
    # ------------------------------------------------------------------

    def describe_tier(self) -> str:
        """Print and return a description of the current creator economy tier."""
        info = get_ce_tier_info(self.tier)
        limit = (
            "Unlimited"
            if info["requests_per_month"] is None
            else f"{info['requests_per_month']:,}"
        )
        lines = [
            f"=== {info['name']} Creator Economy Bot Tier ===",
            f"Price   : ${info['price_usd_monthly']:.2f}/month",
            f"Requests: {limit}/month",
            f"Support : {info['support_level']}",
            "",
            "Creator features:",
        ]
        for feat in info["ce_features"]:
            lines.append(f"  ✓ {feat}")
        lines.append("")
        lines.append("Available tools:")
        for t in info["tools"]:
            lines.append(f"  • {t}")
        output = "\n".join(lines)
        print(output)
        return output

    def show_upgrade_path(self) -> str:
        """Print details about the next available tier upgrade."""
        next_tier = get_upgrade_path(self.tier)
        if next_tier is None:
            msg = f"You are already on the highest tier ({self.config.name})."
        else:
            msg = (
                f"Upgrade to {next_tier.name} for "
                f"${next_tier.price_usd_monthly:.2f}/month to unlock brand deals "
                f"and revenue dashboards."
            )
        print(msg)
        return msg

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _default_tool(self, message: str) -> str:
        available = CE_TOOLS.get(self.tier.value, ["content_ideas"])
        lower = message.lower()
        if "idea" in lower or "content" in lower:
            return "content_ideas"
        if "sponsor" in lower or "pitch" in lower or "brand" in lower:
            return "brand_pitch_generator"
        if "merch" in lower or "store" in lower:
            return "merch_store_setup"
        if "revenue" in lower or "monetiz" in lower:
            return "revenue_dashboard"
        if "hashtag" in lower:
            return "hashtag_generator"
        return available[0] if available else "content_ideas"

    def _check_tool_access(self, tool: str) -> None:
        allowed = CE_TOOLS.get(self.tier.value, [])
        if tool not in allowed:
            raise CreatorEconomyTierError(
                f"Tool '{tool}' is not available on the "
                f"{self.config.name} tier. Upgrade to access it."
            )

    def _check_request_limit(self) -> None:
        limit = self.config.requests_per_month
        if limit is not None and self._request_count >= limit:
            raise CreatorEconomyRequestLimitError(
                f"Monthly request limit of {limit} reached on the "
                f"{self.config.name} tier."
            )

    def _requests_remaining(self) -> int | None:
        limit = self.config.requests_per_month
        if limit is None:
            return None
        return max(0, limit - self._request_count)
