"""
Cryptocurrency Database — static reference data for 66+ coins.

Each entry contains:
  symbol          : ticker symbol
  name            : full name
  category        : e.g. "Layer 1", "DeFi", "Stablecoin", "Meme", etc.
  algorithm       : consensus/mining algorithm
  launch_year     : year first launched
  max_supply      : maximum supply (None = unlimited)
  description     : short plain-language description
  website         : official website URL
  mineable        : whether the coin can be mined (True/False)
  price_usd       : baseline / seed price (updated by PriceFeed at runtime)
  market_cap_usd  : approximate market cap seed value
  circulating_supply: approximate circulating supply
  volume_24h_usd  : approximate 24-hour trading volume seed

GLOBAL AI SOURCES FLOW: used by crypto_bot.py pipeline.
"""

from __future__ import annotations

CRYPTO_DATABASE: dict[str, dict] = {
    # ── Layer 1 / Major ──────────────────────────────────────────────────────
    "BTC": {
        "symbol": "BTC",
        "name": "Bitcoin",
        "category": "Layer 1",
        "algorithm": "SHA-256",
        "launch_year": 2009,
        "max_supply": 21_000_000,
        "mineable": True,
        "price_usd": 67_000.0,
        "market_cap_usd": 1_320_000_000_000,
        "circulating_supply": 19_700_000,
        "volume_24h_usd": 28_000_000_000,
        "description": "The first and largest cryptocurrency by market cap. "
        "A decentralised peer-to-peer electronic cash system.",
        "website": "https://bitcoin.org",
    },
    "ETH": {
        "symbol": "ETH",
        "name": "Ethereum",
        "category": "Layer 1",
        "algorithm": "Proof-of-Stake",
        "launch_year": 2015,
        "max_supply": None,
        "mineable": False,
        "price_usd": 3_500.0,
        "market_cap_usd": 420_000_000_000,
        "circulating_supply": 120_000_000,
        "volume_24h_usd": 15_000_000_000,
        "description": "Programmable blockchain enabling smart contracts and DApps.",
        "website": "https://ethereum.org",
    },
    "SOL": {
        "symbol": "SOL",
        "name": "Solana",
        "category": "Layer 1",
        "algorithm": "Proof-of-History/PoS",
        "launch_year": 2020,
        "max_supply": None,
        "mineable": False,
        "price_usd": 178.0,
        "market_cap_usd": 82_000_000_000,
        "circulating_supply": 461_000_000,
        "volume_24h_usd": 3_500_000_000,
        "description": "High-performance blockchain with sub-second finality.",
        "website": "https://solana.com",
    },
    "BNB": {
        "symbol": "BNB",
        "name": "BNB",
        "category": "Layer 1",
        "algorithm": "Proof-of-Staked-Authority",
        "launch_year": 2017,
        "max_supply": 200_000_000,
        "mineable": False,
        "price_usd": 580.0,
        "market_cap_usd": 86_000_000_000,
        "circulating_supply": 148_000_000,
        "volume_24h_usd": 2_000_000_000,
        "description": "Native token of the BNB Chain / Binance ecosystem.",
        "website": "https://bnbchain.org",
    },
    "XRP": {
        "symbol": "XRP",
        "name": "Ripple",
        "category": "Payments",
        "algorithm": "Ripple Protocol Consensus",
        "launch_year": 2012,
        "max_supply": 100_000_000_000,
        "mineable": False,
        "price_usd": 0.63,
        "market_cap_usd": 34_000_000_000,
        "circulating_supply": 54_000_000_000,
        "volume_24h_usd": 1_500_000_000,
        "description": "Digital payment protocol for fast cross-border transactions.",
        "website": "https://ripple.com",
    },
    "ADA": {
        "symbol": "ADA",
        "name": "Cardano",
        "category": "Layer 1",
        "algorithm": "Ouroboros PoS",
        "launch_year": 2017,
        "max_supply": 45_000_000_000,
        "mineable": False,
        "price_usd": 0.62,
        "market_cap_usd": 22_000_000_000,
        "circulating_supply": 35_500_000_000,
        "volume_24h_usd": 500_000_000,
        "description": "Peer-reviewed, proof-of-stake blockchain platform.",
        "website": "https://cardano.org",
    },
    "DOGE": {
        "symbol": "DOGE",
        "name": "Dogecoin",
        "category": "Meme",
        "algorithm": "Scrypt",
        "launch_year": 2013,
        "max_supply": None,
        "mineable": True,
        "price_usd": 0.125,
        "market_cap_usd": 18_000_000_000,
        "circulating_supply": 143_000_000_000,
        "volume_24h_usd": 800_000_000,
        "description": "Meme-based cryptocurrency with an active community.",
        "website": "https://dogecoin.com",
    },
    "TON": {
        "symbol": "TON",
        "name": "Toncoin",
        "category": "Layer 1",
        "algorithm": "Proof-of-Stake",
        "launch_year": 2021,
        "max_supply": None,
        "mineable": False,
        "price_usd": 7.28,
        "market_cap_usd": 25_000_000_000,
        "circulating_supply": 3_400_000_000,
        "volume_24h_usd": 400_000_000,
        "description": "Fast, scalable blockchain developed by the Telegram team.",
        "website": "https://ton.org",
    },
    "AVAX": {
        "symbol": "AVAX",
        "name": "Avalanche",
        "category": "Layer 1",
        "algorithm": "Avalanche Consensus",
        "launch_year": 2020,
        "max_supply": 720_000_000,
        "mineable": False,
        "price_usd": 42.0,
        "market_cap_usd": 17_000_000_000,
        "circulating_supply": 405_000_000,
        "volume_24h_usd": 700_000_000,
        "description": "Highly scalable platform for DeFi and enterprise blockchains.",
        "website": "https://avax.network",
    },
    "DOT": {
        "symbol": "DOT",
        "name": "Polkadot",
        "category": "Layer 0",
        "algorithm": "Nominated Proof-of-Stake",
        "launch_year": 2020,
        "max_supply": None,
        "mineable": False,
        "price_usd": 8.72,
        "market_cap_usd": 13_000_000_000,
        "circulating_supply": 1_490_000_000,
        "volume_24h_usd": 300_000_000,
        "description": "Multi-chain network enabling interoperability between blockchains.",
        "website": "https://polkadot.network",
    },
    "LINK": {
        "symbol": "LINK",
        "name": "Chainlink",
        "category": "Oracle",
        "algorithm": "Proof-of-Stake",
        "launch_year": 2017,
        "max_supply": 1_000_000_000,
        "mineable": False,
        "price_usd": 18.45,
        "market_cap_usd": 11_000_000_000,
        "circulating_supply": 595_000_000,
        "volume_24h_usd": 450_000_000,
        "description": "Decentralised oracle network providing real-world data to smart contracts.",
        "website": "https://chain.link",
    },
    "MATIC": {
        "symbol": "MATIC",
        "name": "Polygon",
        "category": "Layer 2",
        "algorithm": "Proof-of-Stake",
        "launch_year": 2019,
        "max_supply": 10_000_000_000,
        "mineable": False,
        "price_usd": 0.98,
        "market_cap_usd": 9_500_000_000,
        "circulating_supply": 9_700_000_000,
        "volume_24h_usd": 600_000_000,
        "description": "Ethereum scaling solution using sidechains and rollups.",
        "website": "https://polygon.technology",
    },
    "LTC": {
        "symbol": "LTC",
        "name": "Litecoin",
        "category": "Payments",
        "algorithm": "Scrypt",
        "launch_year": 2011,
        "max_supply": 84_000_000,
        "mineable": True,
        "price_usd": 84.0,
        "market_cap_usd": 6_200_000_000,
        "circulating_supply": 73_900_000,
        "volume_24h_usd": 400_000_000,
        "description": "Silver to Bitcoin's gold — faster block times, lower fees.",
        "website": "https://litecoin.org",
    },
    "ATOM": {
        "symbol": "ATOM",
        "name": "Cosmos",
        "category": "Layer 0",
        "algorithm": "Tendermint BFT",
        "launch_year": 2019,
        "max_supply": None,
        "mineable": False,
        "price_usd": 9.50,
        "market_cap_usd": 3_700_000_000,
        "circulating_supply": 390_000_000,
        "volume_24h_usd": 200_000_000,
        "description": "Interoperable blockchain ecosystem ('Internet of Blockchains').",
        "website": "https://cosmos.network",
    },
    "UNI": {
        "symbol": "UNI",
        "name": "Uniswap",
        "category": "DeFi",
        "algorithm": "Proof-of-Stake (governance)",
        "launch_year": 2018,
        "max_supply": 1_000_000_000,
        "mineable": False,
        "price_usd": 11.20,
        "market_cap_usd": 6_700_000_000,
        "circulating_supply": 598_000_000,
        "volume_24h_usd": 250_000_000,
        "description": "Governance token for the largest decentralised exchange protocol.",
        "website": "https://uniswap.org",
    },
    "AAVE": {
        "symbol": "AAVE",
        "name": "Aave",
        "category": "DeFi",
        "algorithm": "Proof-of-Stake (governance)",
        "launch_year": 2020,
        "max_supply": 16_000_000,
        "mineable": False,
        "price_usd": 185.0,
        "market_cap_usd": 2_780_000_000,
        "circulating_supply": 15_000_000,
        "volume_24h_usd": 150_000_000,
        "description": "Decentralised lending and borrowing protocol.",
        "website": "https://aave.com",
    },
    "XMR": {
        "symbol": "XMR",
        "name": "Monero",
        "category": "Privacy",
        "algorithm": "RandomX",
        "launch_year": 2014,
        "max_supply": None,
        "mineable": True,
        "price_usd": 175.0,
        "market_cap_usd": 3_200_000_000,
        "circulating_supply": 18_300_000,
        "volume_24h_usd": 100_000_000,
        "description": "Privacy-focused cryptocurrency with untraceable transactions.",
        "website": "https://getmonero.org",
    },
    "ZEC": {
        "symbol": "ZEC",
        "name": "Zcash",
        "category": "Privacy",
        "algorithm": "Equihash",
        "launch_year": 2016,
        "max_supply": 21_000_000,
        "mineable": True,
        "price_usd": 28.0,
        "market_cap_usd": 470_000_000,
        "circulating_supply": 17_000_000,
        "volume_24h_usd": 40_000_000,
        "description": "Privacy coin using zk-SNARKs for shielded transactions.",
        "website": "https://z.cash",
    },
    "ALGO": {
        "symbol": "ALGO",
        "name": "Algorand",
        "category": "Layer 1",
        "algorithm": "Pure Proof-of-Stake",
        "launch_year": 2019,
        "max_supply": 10_000_000_000,
        "mineable": False,
        "price_usd": 0.21,
        "market_cap_usd": 1_700_000_000,
        "circulating_supply": 8_000_000_000,
        "volume_24h_usd": 90_000_000,
        "description": "Carbon-negative Layer-1 with instant transaction finality.",
        "website": "https://algorand.com",
    },
    "VET": {
        "symbol": "VET",
        "name": "VeChain",
        "category": "Supply Chain",
        "algorithm": "Proof-of-Authority",
        "launch_year": 2018,
        "max_supply": 86_712_634_466,
        "mineable": False,
        "price_usd": 0.035,
        "market_cap_usd": 2_800_000_000,
        "circulating_supply": 80_000_000_000,
        "volume_24h_usd": 70_000_000,
        "description": "Enterprise-grade supply-chain and IoT blockchain.",
        "website": "https://vechain.org",
    },
    "FIL": {
        "symbol": "FIL",
        "name": "Filecoin",
        "category": "Storage",
        "algorithm": "Proof-of-Spacetime",
        "launch_year": 2020,
        "max_supply": 2_000_000_000,
        "mineable": True,
        "price_usd": 6.80,
        "market_cap_usd": 3_800_000_000,
        "circulating_supply": 570_000_000,
        "volume_24h_usd": 200_000_000,
        "description": "Decentralised storage network incentivising data hosting.",
        "website": "https://filecoin.io",
    },
    "ICP": {
        "symbol": "ICP",
        "name": "Internet Computer",
        "category": "Layer 1",
        "algorithm": "Threshold Relay",
        "launch_year": 2021,
        "max_supply": None,
        "mineable": False,
        "price_usd": 12.0,
        "market_cap_usd": 5_600_000_000,
        "circulating_supply": 467_000_000,
        "volume_24h_usd": 150_000_000,
        "description": "DFINITY's internet-native blockchain for hosting web services.",
        "website": "https://dfinity.org",
    },
    "NEAR": {
        "symbol": "NEAR",
        "name": "NEAR Protocol",
        "category": "Layer 1",
        "algorithm": "Nightshade Sharding / PoS",
        "launch_year": 2020,
        "max_supply": None,
        "mineable": False,
        "price_usd": 7.20,
        "market_cap_usd": 8_000_000_000,
        "circulating_supply": 1_120_000_000,
        "volume_24h_usd": 300_000_000,
        "description": "Developer-friendly sharded blockchain with human-readable accounts.",
        "website": "https://near.org",
    },
    "FTM": {
        "symbol": "FTM",
        "name": "Fantom",
        "category": "Layer 1",
        "algorithm": "Lachesis PoS",
        "launch_year": 2019,
        "max_supply": 3_175_000_000,
        "mineable": False,
        "price_usd": 1.05,
        "market_cap_usd": 2_950_000_000,
        "circulating_supply": 2_800_000_000,
        "volume_24h_usd": 250_000_000,
        "description": "DAG-based smart contract platform with fast finality.",
        "website": "https://fantom.foundation",
    },
    "HBAR": {
        "symbol": "HBAR",
        "name": "Hedera",
        "category": "Layer 1",
        "algorithm": "Hashgraph (PoS)",
        "launch_year": 2019,
        "max_supply": 50_000_000_000,
        "mineable": False,
        "price_usd": 0.095,
        "market_cap_usd": 3_700_000_000,
        "circulating_supply": 38_600_000_000,
        "volume_24h_usd": 150_000_000,
        "description": "Enterprise-grade distributed ledger using hashgraph consensus.",
        "website": "https://hedera.com",
    },
    "EGLD": {
        "symbol": "EGLD",
        "name": "MultiversX",
        "category": "Layer 1",
        "algorithm": "Secure Proof-of-Stake",
        "launch_year": 2020,
        "max_supply": 31_415_926,
        "mineable": False,
        "price_usd": 42.0,
        "market_cap_usd": 1_140_000_000,
        "circulating_supply": 27_000_000,
        "volume_24h_usd": 60_000_000,
        "description": "High-throughput sharded blockchain (formerly Elrond).",
        "website": "https://multiversx.com",
    },
    "FLOW": {
        "symbol": "FLOW",
        "name": "Flow",
        "category": "NFT / Gaming",
        "algorithm": "Proof-of-Stake",
        "launch_year": 2020,
        "max_supply": None,
        "mineable": False,
        "price_usd": 1.10,
        "market_cap_usd": 1_130_000_000,
        "circulating_supply": 1_030_000_000,
        "volume_24h_usd": 50_000_000,
        "description": "Blockchain designed for games and digital collectibles (NBA Top Shot).",
        "website": "https://flow.com",
    },
    "THETA": {
        "symbol": "THETA",
        "name": "Theta Network",
        "category": "Media",
        "algorithm": "Proof-of-Stake",
        "launch_year": 2019,
        "max_supply": 1_000_000_000,
        "mineable": False,
        "price_usd": 2.40,
        "market_cap_usd": 2_400_000_000,
        "circulating_supply": 1_000_000_000,
        "volume_24h_usd": 80_000_000,
        "description": "Decentralised video streaming network.",
        "website": "https://thetatoken.org",
    },
    "XLM": {
        "symbol": "XLM",
        "name": "Stellar",
        "category": "Payments",
        "algorithm": "Stellar Consensus Protocol",
        "launch_year": 2014,
        "max_supply": 50_001_806_812,
        "mineable": False,
        "price_usd": 0.115,
        "market_cap_usd": 3_300_000_000,
        "circulating_supply": 28_700_000_000,
        "volume_24h_usd": 200_000_000,
        "description": "Open payment network connecting banks and people globally.",
        "website": "https://stellar.org",
    },
    "TRX": {
        "symbol": "TRX",
        "name": "TRON",
        "category": "Layer 1",
        "algorithm": "Delegated Proof-of-Stake",
        "launch_year": 2018,
        "max_supply": None,
        "mineable": False,
        "price_usd": 0.125,
        "market_cap_usd": 11_000_000_000,
        "circulating_supply": 88_000_000_000,
        "volume_24h_usd": 700_000_000,
        "description": "High-throughput blockchain for entertainment and content sharing.",
        "website": "https://tron.network",
    },
    "EOS": {
        "symbol": "EOS",
        "name": "EOS",
        "category": "Layer 1",
        "algorithm": "Delegated Proof-of-Stake",
        "launch_year": 2018,
        "max_supply": None,
        "mineable": False,
        "price_usd": 0.85,
        "market_cap_usd": 960_000_000,
        "circulating_supply": 1_130_000_000,
        "volume_24h_usd": 100_000_000,
        "description": "Enterprise-grade DPoS blockchain for decentralised applications.",
        "website": "https://eosnetwork.com",
    },
    # ── Stablecoins ──────────────────────────────────────────────────────────
    "USDT": {
        "symbol": "USDT",
        "name": "Tether",
        "category": "Stablecoin",
        "algorithm": "n/a",
        "launch_year": 2014,
        "max_supply": None,
        "mineable": False,
        "price_usd": 1.00,
        "market_cap_usd": 112_000_000_000,
        "circulating_supply": 112_000_000_000,
        "volume_24h_usd": 60_000_000_000,
        "description": "USD-pegged stablecoin, the most traded crypto asset.",
        "website": "https://tether.to",
    },
    "USDC": {
        "symbol": "USDC",
        "name": "USD Coin",
        "category": "Stablecoin",
        "algorithm": "n/a",
        "launch_year": 2018,
        "max_supply": None,
        "mineable": False,
        "price_usd": 1.00,
        "market_cap_usd": 43_000_000_000,
        "circulating_supply": 43_000_000_000,
        "volume_24h_usd": 8_000_000_000,
        "description": "Regulated USD stablecoin issued by Circle.",
        "website": "https://circle.com/usdc",
    },
    "DAI": {
        "symbol": "DAI",
        "name": "Dai",
        "category": "Stablecoin",
        "algorithm": "n/a (MakerDAO governance)",
        "launch_year": 2017,
        "max_supply": None,
        "mineable": False,
        "price_usd": 1.00,
        "market_cap_usd": 5_200_000_000,
        "circulating_supply": 5_200_000_000,
        "volume_24h_usd": 700_000_000,
        "description": "Decentralised, crypto-collateralised stablecoin by MakerDAO.",
        "website": "https://makerdao.com",
    },
    # ── DeFi ──────────────────────────────────────────────────────────────────
    "MKR": {
        "symbol": "MKR",
        "name": "Maker",
        "category": "DeFi",
        "algorithm": "Proof-of-Stake (governance)",
        "launch_year": 2017,
        "max_supply": 1_005_577,
        "mineable": False,
        "price_usd": 2_800.0,
        "market_cap_usd": 2_800_000_000,
        "circulating_supply": 1_000_000,
        "volume_24h_usd": 80_000_000,
        "description": "Governance token of MakerDAO, creator of the DAI stablecoin.",
        "website": "https://makerdao.com",
    },
    "COMP": {
        "symbol": "COMP",
        "name": "Compound",
        "category": "DeFi",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 10_000_000,
        "mineable": False,
        "price_usd": 52.0,
        "market_cap_usd": 370_000_000,
        "circulating_supply": 7_100_000,
        "volume_24h_usd": 30_000_000,
        "description": "Algorithmic money-market protocol on Ethereum.",
        "website": "https://compound.finance",
    },
    "SNX": {
        "symbol": "SNX",
        "name": "Synthetix",
        "category": "DeFi",
        "algorithm": "n/a",
        "launch_year": 2018,
        "max_supply": None,
        "mineable": False,
        "price_usd": 3.40,
        "market_cap_usd": 1_100_000_000,
        "circulating_supply": 320_000_000,
        "volume_24h_usd": 70_000_000,
        "description": "Decentralised synthetic asset issuance protocol.",
        "website": "https://synthetix.io",
    },
    "CRV": {
        "symbol": "CRV",
        "name": "Curve DAO Token",
        "category": "DeFi",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 3_030_303_031,
        "mineable": False,
        "price_usd": 0.47,
        "market_cap_usd": 600_000_000,
        "circulating_supply": 1_270_000_000,
        "volume_24h_usd": 100_000_000,
        "description": "AMM optimised for stablecoin trading.",
        "website": "https://curve.fi",
    },
    "1INCH": {
        "symbol": "1INCH",
        "name": "1inch",
        "category": "DeFi",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 1_500_000_000,
        "mineable": False,
        "price_usd": 0.40,
        "market_cap_usd": 390_000_000,
        "circulating_supply": 990_000_000,
        "volume_24h_usd": 50_000_000,
        "description": "DEX aggregator routing trades across multiple AMMs.",
        "website": "https://1inch.io",
    },
    # ── NFT / Metaverse ───────────────────────────────────────────────────────
    "SAND": {
        "symbol": "SAND",
        "name": "The Sandbox",
        "category": "Metaverse",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 3_000_000_000,
        "mineable": False,
        "price_usd": 0.48,
        "market_cap_usd": 1_100_000_000,
        "circulating_supply": 2_200_000_000,
        "volume_24h_usd": 120_000_000,
        "description": "Virtual world where players build and monetise experiences.",
        "website": "https://sandbox.game",
    },
    "MANA": {
        "symbol": "MANA",
        "name": "Decentraland",
        "category": "Metaverse",
        "algorithm": "n/a",
        "launch_year": 2017,
        "max_supply": 2_644_403_343,
        "mineable": False,
        "price_usd": 0.50,
        "market_cap_usd": 950_000_000,
        "circulating_supply": 1_890_000_000,
        "volume_24h_usd": 80_000_000,
        "description": "Virtual reality platform on Ethereum where users own land.",
        "website": "https://decentraland.org",
    },
    "AXS": {
        "symbol": "AXS",
        "name": "Axie Infinity",
        "category": "NFT / Gaming",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 270_000_000,
        "mineable": False,
        "price_usd": 7.50,
        "market_cap_usd": 1_100_000_000,
        "circulating_supply": 145_000_000,
        "volume_24h_usd": 80_000_000,
        "description": "Play-to-earn NFT game powered by the Ronin sidechain.",
        "website": "https://axieinfinity.com",
    },
    # ── Mining / PoW ─────────────────────────────────────────────────────────
    "RVN": {
        "symbol": "RVN",
        "name": "Ravencoin",
        "category": "Mining",
        "algorithm": "KawPoW",
        "launch_year": 2018,
        "max_supply": 21_000_000_000,
        "mineable": True,
        "price_usd": 0.025,
        "market_cap_usd": 380_000_000,
        "circulating_supply": 15_000_000_000,
        "volume_24h_usd": 20_000_000,
        "description": "Asset-transfer-focused UTXO chain with ASIC-resistant mining.",
        "website": "https://ravencoin.org",
    },
    "ERG": {
        "symbol": "ERG",
        "name": "Ergo",
        "category": "Mining",
        "algorithm": "Autolykos2",
        "launch_year": 2019,
        "max_supply": 97_739_924,
        "mineable": True,
        "price_usd": 1.85,
        "market_cap_usd": 190_000_000,
        "circulating_supply": 97_000_000,
        "volume_24h_usd": 8_000_000,
        "description": "Research-driven PoW platform with sigma protocols.",
        "website": "https://ergoplatform.org",
    },
    "FLUX": {
        "symbol": "FLUX",
        "name": "Flux",
        "category": "Mining",
        "algorithm": "ZelHash",
        "launch_year": 2018,
        "max_supply": 440_000_000,
        "mineable": True,
        "price_usd": 0.65,
        "market_cap_usd": 260_000_000,
        "circulating_supply": 400_000_000,
        "volume_24h_usd": 15_000_000,
        "description": "Decentralised cloud computing powered by a PoW blockchain.",
        "website": "https://runonflux.io",
    },
    "KAS": {
        "symbol": "KAS",
        "name": "Kaspa",
        "category": "Mining",
        "algorithm": "kHeavyHash",
        "launch_year": 2021,
        "max_supply": 28_700_000_000,
        "mineable": True,
        "price_usd": 0.12,
        "market_cap_usd": 2_900_000_000,
        "circulating_supply": 24_000_000_000,
        "volume_24h_usd": 100_000_000,
        "description": "High-speed PoW coin using the GHOSTDAG blockDAG protocol.",
        "website": "https://kaspa.org",
    },
    "ALPH": {
        "symbol": "ALPH",
        "name": "Alephium",
        "category": "Mining",
        "algorithm": "Blake3 (sharded PoW)",
        "launch_year": 2021,
        "max_supply": 1_000_000_000,
        "mineable": True,
        "price_usd": 1.60,
        "market_cap_usd": 220_000_000,
        "circulating_supply": 137_000_000,
        "volume_24h_usd": 10_000_000,
        "description": "Sharded UTXO-based PoW blockchain with stateful UTXO model.",
        "website": "https://alephium.org",
    },
    "BEAM": {
        "symbol": "BEAM",
        "name": "Beam",
        "category": "Privacy / Mining",
        "algorithm": "BeamHash III",
        "launch_year": 2019,
        "max_supply": 262_800_000,
        "mineable": True,
        "price_usd": 0.038,
        "market_cap_usd": 38_000_000,
        "circulating_supply": 1_000_000_000,
        "volume_24h_usd": 5_000_000,
        "description": "Privacy coin using MimbleWimble protocol.",
        "website": "https://beam.mw",
    },
    "GRIN": {
        "symbol": "GRIN",
        "name": "Grin",
        "category": "Privacy / Mining",
        "algorithm": "Cuckoo Cycle",
        "launch_year": 2019,
        "max_supply": None,
        "mineable": True,
        "price_usd": 0.08,
        "market_cap_usd": 40_000_000,
        "circulating_supply": 500_000_000,
        "volume_24h_usd": 2_000_000,
        "description": "MimbleWimble-based privacy coin with no premine.",
        "website": "https://grin.mw",
    },
    "FIRO": {
        "symbol": "FIRO",
        "name": "Firo",
        "category": "Privacy / Mining",
        "algorithm": "FiroPoW",
        "launch_year": 2016,
        "max_supply": 21_400_000,
        "mineable": True,
        "price_usd": 2.20,
        "market_cap_usd": 30_000_000,
        "circulating_supply": 13_800_000,
        "volume_24h_usd": 2_000_000,
        "description": "Privacy coin using Lelantus zero-knowledge proofs.",
        "website": "https://firo.org",
    },
    "VTC": {
        "symbol": "VTC",
        "name": "Vertcoin",
        "category": "Mining",
        "algorithm": "Verthash",
        "launch_year": 2014,
        "max_supply": 84_000_000,
        "mineable": True,
        "price_usd": 0.13,
        "market_cap_usd": 6_000_000,
        "circulating_supply": 46_000_000,
        "volume_24h_usd": 500_000,
        "description": "ASIC-resistant PoW coin designed for GPU miners.",
        "website": "https://vertcoin.org",
    },
    # ── Exchange Tokens ───────────────────────────────────────────────────────
    "CRO": {
        "symbol": "CRO",
        "name": "Cronos",
        "category": "Exchange Token",
        "algorithm": "Proof-of-Authority",
        "launch_year": 2018,
        "max_supply": 30_263_013_692,
        "mineable": False,
        "price_usd": 0.12,
        "market_cap_usd": 3_100_000_000,
        "circulating_supply": 25_700_000_000,
        "volume_24h_usd": 80_000_000,
        "description": "Native token of the Crypto.com chain.",
        "website": "https://crypto.com",
    },
    "OKB": {
        "symbol": "OKB",
        "name": "OKB",
        "category": "Exchange Token",
        "algorithm": "n/a",
        "launch_year": 2019,
        "max_supply": None,
        "mineable": False,
        "price_usd": 48.0,
        "market_cap_usd": 2_900_000_000,
        "circulating_supply": 60_000_000,
        "volume_24h_usd": 100_000_000,
        "description": "Utility token for OKX exchange ecosystem.",
        "website": "https://okx.com",
    },
    # ── AI / Data ─────────────────────────────────────────────────────────────
    "GRT": {
        "symbol": "GRT",
        "name": "The Graph",
        "category": "Data / AI",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 10_788_004_317,
        "mineable": False,
        "price_usd": 0.19,
        "market_cap_usd": 1_810_000_000,
        "circulating_supply": 9_550_000_000,
        "volume_24h_usd": 80_000_000,
        "description": "Indexing protocol for querying blockchain data.",
        "website": "https://thegraph.com",
    },
    "FET": {
        "symbol": "FET",
        "name": "Fetch.ai",
        "category": "Data / AI",
        "algorithm": "n/a",
        "launch_year": 2019,
        "max_supply": 1_152_997_575,
        "mineable": False,
        "price_usd": 2.35,
        "market_cap_usd": 2_400_000_000,
        "circulating_supply": 1_020_000_000,
        "volume_24h_usd": 150_000_000,
        "description": "AI-powered autonomous agent network for DeFi and IoT.",
        "website": "https://fetch.ai",
    },
    "OCEAN": {
        "symbol": "OCEAN",
        "name": "Ocean Protocol",
        "category": "Data / AI",
        "algorithm": "n/a",
        "launch_year": 2019,
        "max_supply": 1_410_000_000,
        "mineable": False,
        "price_usd": 0.95,
        "market_cap_usd": 540_000_000,
        "circulating_supply": 568_000_000,
        "volume_24h_usd": 40_000_000,
        "description": "Decentralised data exchange protocol with AI integrations.",
        "website": "https://oceanprotocol.com",
    },
    "RNDR": {
        "symbol": "RNDR",
        "name": "Render Network",
        "category": "Data / AI",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 536_870_912,
        "mineable": False,
        "price_usd": 8.20,
        "market_cap_usd": 3_300_000_000,
        "circulating_supply": 400_000_000,
        "volume_24h_usd": 200_000_000,
        "description": "Distributed GPU rendering network for 3D / AI workloads.",
        "website": "https://rendernetwork.com",
    },
    # ── Meme ─────────────────────────────────────────────────────────────────
    "SHIB": {
        "symbol": "SHIB",
        "name": "Shiba Inu",
        "category": "Meme",
        "algorithm": "n/a",
        "launch_year": 2020,
        "max_supply": 999_990_000_000_000,
        "mineable": False,
        "price_usd": 0.0000265,
        "market_cap_usd": 15_600_000_000,
        "circulating_supply": 589_000_000_000_000,
        "volume_24h_usd": 400_000_000,
        "description": "Ethereum-based meme coin and 'Dogecoin killer'.",
        "website": "https://shibatoken.com",
    },
    "PEPE": {
        "symbol": "PEPE",
        "name": "Pepe",
        "category": "Meme",
        "algorithm": "n/a",
        "launch_year": 2023,
        "max_supply": 420_690_000_000_000,
        "mineable": False,
        "price_usd": 0.0000142,
        "market_cap_usd": 5_900_000_000,
        "circulating_supply": 420_690_000_000_000,
        "volume_24h_usd": 600_000_000,
        "description": "Meme coin based on the iconic Pepe the Frog internet meme.",
        "website": "https://pepe.vip",
    },
    # ── Infrastructure ────────────────────────────────────────────────────────
    "AR": {
        "symbol": "AR",
        "name": "Arweave",
        "category": "Storage",
        "algorithm": "Proof-of-Access (PoW variant)",
        "launch_year": 2018,
        "max_supply": 66_000_000,
        "mineable": True,
        "price_usd": 32.0,
        "market_cap_usd": 2_100_000_000,
        "circulating_supply": 65_500_000,
        "volume_24h_usd": 90_000_000,
        "description": "Permanent, decentralised data storage network.",
        "website": "https://arweave.org",
    },
    "HNT": {
        "symbol": "HNT",
        "name": "Helium",
        "category": "IoT",
        "algorithm": "Proof-of-Coverage",
        "launch_year": 2019,
        "max_supply": 223_000_000,
        "mineable": False,
        "price_usd": 7.80,
        "market_cap_usd": 1_300_000_000,
        "circulating_supply": 166_000_000,
        "volume_24h_usd": 40_000_000,
        "description": "Decentralised wireless network for IoT devices.",
        "website": "https://helium.com",
    },
    "WLD": {
        "symbol": "WLD",
        "name": "Worldcoin",
        "category": "Identity / AI",
        "algorithm": "Proof-of-Personhood",
        "launch_year": 2023,
        "max_supply": 10_000_000_000,
        "mineable": False,
        "price_usd": 4.80,
        "market_cap_usd": 830_000_000,
        "circulating_supply": 172_000_000,
        "volume_24h_usd": 180_000_000,
        "description": "Identity and financial protocol using iris-scanning orbs.",
        "website": "https://worldcoin.org",
    },
    "INJ": {
        "symbol": "INJ",
        "name": "Injective",
        "category": "DeFi / Layer 1",
        "algorithm": "Tendermint PoS",
        "launch_year": 2020,
        "max_supply": 100_000_000,
        "mineable": False,
        "price_usd": 28.0,
        "market_cap_usd": 2_800_000_000,
        "circulating_supply": 100_000_000,
        "volume_24h_usd": 200_000_000,
        "description": "Finance-focused L1 blockchain with built-in order book DEX.",
        "website": "https://injective.com",
    },
    "SUI": {
        "symbol": "SUI",
        "name": "Sui",
        "category": "Layer 1",
        "algorithm": "Narwhal & Bullshark / PoS",
        "launch_year": 2023,
        "max_supply": 10_000_000_000,
        "mineable": False,
        "price_usd": 1.75,
        "market_cap_usd": 4_800_000_000,
        "circulating_supply": 2_750_000_000,
        "volume_24h_usd": 500_000_000,
        "description": "High-throughput L1 from ex-Meta Diem engineers.",
        "website": "https://sui.io",
    },
    "APT": {
        "symbol": "APT",
        "name": "Aptos",
        "category": "Layer 1",
        "algorithm": "AptosBFT (PoS)",
        "launch_year": 2022,
        "max_supply": None,
        "mineable": False,
        "price_usd": 9.50,
        "market_cap_usd": 4_100_000_000,
        "circulating_supply": 430_000_000,
        "volume_24h_usd": 280_000_000,
        "description": "Move-based L1 developed by former Meta / Diem team.",
        "website": "https://aptoslabs.com",
    },
    "SEI": {
        "symbol": "SEI",
        "name": "Sei",
        "category": "Layer 1",
        "algorithm": "Twin-Turbo Consensus (PoS)",
        "launch_year": 2023,
        "max_supply": 10_000_000_000,
        "mineable": False,
        "price_usd": 0.52,
        "market_cap_usd": 2_500_000_000,
        "circulating_supply": 4_800_000_000,
        "volume_24h_usd": 200_000_000,
        "description": "Fast L1 optimised for trading applications.",
        "website": "https://sei.io",
    },
    "OP": {
        "symbol": "OP",
        "name": "Optimism",
        "category": "Layer 2",
        "algorithm": "Optimistic Rollup",
        "launch_year": 2022,
        "max_supply": 4_294_967_296,
        "mineable": False,
        "price_usd": 2.40,
        "market_cap_usd": 2_500_000_000,
        "circulating_supply": 1_040_000_000,
        "volume_24h_usd": 200_000_000,
        "description": "Ethereum L2 using optimistic rollups for cheap, fast transactions.",
        "website": "https://optimism.io",
    },
    "ARB": {
        "symbol": "ARB",
        "name": "Arbitrum",
        "category": "Layer 2",
        "algorithm": "Optimistic Rollup",
        "launch_year": 2023,
        "max_supply": 10_000_000_000,
        "mineable": False,
        "price_usd": 1.15,
        "market_cap_usd": 3_700_000_000,
        "circulating_supply": 3_200_000_000,
        "volume_24h_usd": 350_000_000,
        "description": "Leading Ethereum L2 scaling solution by Offchain Labs.",
        "website": "https://arbitrum.io",
    },
    "STX": {
        "symbol": "STX",
        "name": "Stacks",
        "category": "Layer 2 (Bitcoin)",
        "algorithm": "Proof-of-Transfer",
        "launch_year": 2021,
        "max_supply": 1_818_000_000,
        "mineable": False,
        "price_usd": 2.10,
        "market_cap_usd": 3_200_000_000,
        "circulating_supply": 1_520_000_000,
        "volume_24h_usd": 100_000_000,
        "description": "Bitcoin L2 bringing smart contracts to Bitcoin.",
        "website": "https://stacks.co",
    },
    "IMX": {
        "symbol": "IMX",
        "name": "Immutable X",
        "category": "Layer 2 / NFT",
        "algorithm": "ZK-Rollup",
        "launch_year": 2021,
        "max_supply": 2_000_000_000,
        "mineable": False,
        "price_usd": 2.20,
        "market_cap_usd": 3_400_000_000,
        "circulating_supply": 1_540_000_000,
        "volume_24h_usd": 120_000_000,
        "description": "ZK-rollup L2 for NFT gaming and marketplaces.",
        "website": "https://immutable.com",
    },
    "KAVA": {
        "symbol": "KAVA",
        "name": "Kava",
        "category": "DeFi",
        "algorithm": "Tendermint PoS",
        "launch_year": 2019,
        "max_supply": None,
        "mineable": False,
        "price_usd": 0.75,
        "market_cap_usd": 530_000_000,
        "circulating_supply": 706_000_000,
        "volume_24h_usd": 40_000_000,
        "description": "Cross-chain DeFi platform with lending and stablecoin minting.",
        "website": "https://kava.io",
    },
    "ROSE": {
        "symbol": "ROSE",
        "name": "Oasis Network",
        "category": "Privacy / Layer 1",
        "algorithm": "Tendermint PoS",
        "launch_year": 2020,
        "max_supply": 10_000_000_000,
        "mineable": False,
        "price_usd": 0.095,
        "market_cap_usd": 650_000_000,
        "circulating_supply": 6_800_000_000,
        "volume_24h_usd": 60_000_000,
        "description": "Privacy-enabling L1 for data-sensitive DeFi and AI.",
        "website": "https://oasisprotocol.org",
    },
    "CFX": {
        "symbol": "CFX",
        "name": "Conflux",
        "category": "Layer 1",
        "algorithm": "Greedy Heaviest Adaptive SubTree (PoW+PoS)",
        "launch_year": 2021,
        "max_supply": 5_000_000_000,
        "mineable": True,
        "price_usd": 0.22,
        "market_cap_usd": 750_000_000,
        "circulating_supply": 3_400_000_000,
        "volume_24h_usd": 80_000_000,
        "description": "High-throughput tree-graph consensus blockchain.",
        "website": "https://confluxnetwork.org",
    },
}


def get_coin(symbol: str) -> dict | None:
    """Return coin data for *symbol* (case-insensitive), or None if not found."""
    return CRYPTO_DATABASE.get(symbol.upper())


def list_coins(category: str | None = None) -> list[dict]:
    """Return all coins, optionally filtered by category."""
    coins = list(CRYPTO_DATABASE.values())
    if category:
        coins = [c for c in coins if c["category"].lower() == category.lower()]
    return coins


def list_mineable_coins() -> list[dict]:
    """Return all coins that can be mined."""
    return [c for c in CRYPTO_DATABASE.values() if c["mineable"]]


def search_coins(query: str) -> list[dict]:
    """Return coins whose symbol or name contains *query* (case-insensitive)."""
    q = query.lower()
    return [
        c
        for c in CRYPTO_DATABASE.values()
        if q in c["symbol"].lower() or q in c["name"].lower()
    ]


def list_categories() -> list[str]:
    """Return sorted unique categories."""
    return sorted({c["category"] for c in CRYPTO_DATABASE.values()})
