"""RevenueEngine: track and report revenue generated by bots."""

import logging
from typing import Dict, List


class RevenueEngine:
    """Tracks revenue entries and exposes aggregated reporting."""

    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self._entries: List[Dict] = []

    def record(self, source: str, amount: float, currency: str = "USD") -> None:
        """Record a revenue event."""
        entry = {"source": source, "amount": amount, "currency": currency}
        self._entries.append(entry)
        self.logger.info("Revenue recorded: %s %.2f %s", source, amount, currency)

    def total(self, currency: str = "USD") -> float:
        """Return total revenue for a given currency."""
        return sum(e["amount"] for e in self._entries if e["currency"] == currency)

    def report(self) -> List[Dict]:
        """Return all revenue entries."""
        return list(self._entries)

    def reset(self) -> None:
        """Clear all recorded revenue entries."""
        self._entries.clear()
