"""
Open Claw Bot — Strategy Engine

Analyses market and operational data to generate Open Claw strategies for
bots and clients.  Strategies are ranked by expected ROI, risk score,
and alignment with client goals.

Adheres to the Dreamcobots GlobalAISourcesFlow framework.
See framework/global_ai_sources_flow.py for the full pipeline specification.
"""

from __future__ import annotations

import statistics
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class StrategyType(Enum):
    AGGRESSIVE = "aggressive"
    BALANCED = "balanced"
    CONSERVATIVE = "conservative"
    SCALPING = "scalping"
    LONG_TERM = "long_term"
    ARBITRAGE = "arbitrage"
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"


class StrategyStatus(Enum):
    DRAFT = "draft"
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    ARCHIVED = "archived"


class RiskLevel(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    EXTREME = "extreme"


@dataclass
class DataPoint:
    """A single data observation used for strategy analysis."""

    timestamp: str
    metric: str
    value: float
    source: str = ""
    tags: list = field(default_factory=list)


@dataclass
class Strategy:
    """An Open Claw strategy generated by the engine."""

    strategy_id: str
    name: str
    strategy_type: StrategyType
    description: str
    risk_level: RiskLevel
    expected_roi_pct: float
    confidence_score: float          # 0.0 – 1.0
    rules: list                      # list of rule dicts
    custom_params: dict = field(default_factory=dict)
    status: StrategyStatus = StrategyStatus.DRAFT
    client_id: Optional[str] = None
    bot_id: Optional[str] = None
    performance_history: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "type": self.strategy_type.value,
            "description": self.description,
            "risk_level": self.risk_level.value,
            "expected_roi_pct": self.expected_roi_pct,
            "confidence_score": self.confidence_score,
            "rules": self.rules,
            "custom_params": self.custom_params,
            "status": self.status.value,
            "client_id": self.client_id,
            "bot_id": self.bot_id,
        }


# ---------------------------------------------------------------------------
# Strategy rule templates
# ---------------------------------------------------------------------------

STRATEGY_RULE_TEMPLATES: dict = {
    StrategyType.AGGRESSIVE: [
        {"rule": "entry_on_breakout", "threshold_pct": 2.0},
        {"rule": "stop_loss_pct", "value": 5.0},
        {"rule": "take_profit_pct", "value": 15.0},
        {"rule": "max_position_size_pct", "value": 20.0},
    ],
    StrategyType.BALANCED: [
        {"rule": "entry_on_trend_confirm", "periods": 3},
        {"rule": "stop_loss_pct", "value": 3.0},
        {"rule": "take_profit_pct", "value": 9.0},
        {"rule": "max_position_size_pct", "value": 10.0},
    ],
    StrategyType.CONSERVATIVE: [
        {"rule": "entry_on_oversold", "rsi_threshold": 30},
        {"rule": "stop_loss_pct", "value": 1.5},
        {"rule": "take_profit_pct", "value": 4.5},
        {"rule": "max_position_size_pct", "value": 5.0},
    ],
    StrategyType.SCALPING: [
        {"rule": "entry_on_micro_momentum", "seconds": 30},
        {"rule": "stop_loss_pct", "value": 0.5},
        {"rule": "take_profit_pct", "value": 1.0},
        {"rule": "max_trades_per_hour", "value": 20},
    ],
    StrategyType.LONG_TERM: [
        {"rule": "entry_on_monthly_low", "lookback_months": 6},
        {"rule": "stop_loss_pct", "value": 10.0},
        {"rule": "take_profit_pct", "value": 40.0},
        {"rule": "rebalance_quarterly", "value": True},
    ],
    StrategyType.ARBITRAGE: [
        {"rule": "detect_spread_threshold_pct", "value": 0.3},
        {"rule": "simultaneous_entry_exit", "value": True},
        {"rule": "max_latency_ms", "value": 50},
    ],
    StrategyType.MOMENTUM: [
        {"rule": "entry_on_volume_surge", "multiplier": 2.0},
        {"rule": "stop_loss_pct", "value": 2.5},
        {"rule": "take_profit_pct", "value": 8.0},
        {"rule": "trailing_stop_pct", "value": 2.0},
    ],
    StrategyType.MEAN_REVERSION: [
        {"rule": "entry_on_z_score", "threshold": 2.0},
        {"rule": "stop_loss_pct", "value": 2.0},
        {"rule": "take_profit_pct", "value": 5.0},
        {"rule": "exit_at_mean", "value": True},
    ],
}

RISK_PARAMS: dict = {
    RiskLevel.LOW: {"roi_base": 3.0, "roi_max": 8.0, "confidence_boost": 0.1},
    RiskLevel.MEDIUM: {"roi_base": 8.0, "roi_max": 20.0, "confidence_boost": 0.0},
    RiskLevel.HIGH: {"roi_base": 15.0, "roi_max": 40.0, "confidence_boost": -0.1},
    RiskLevel.EXTREME: {"roi_base": 25.0, "roi_max": 80.0, "confidence_boost": -0.2},
}


class StrategyEngine:
    """
    Open Claw Strategy Engine.

    Analyses input data and generates ranked strategies for bots and clients.
    Strategies can be templated or fully customised.
    """

    def __init__(self) -> None:
        self._strategies: dict[str, Strategy] = {}
        self._counter: int = 0
        self._data_buffer: list[DataPoint] = []

    # ------------------------------------------------------------------
    # Data ingestion
    # ------------------------------------------------------------------

    def ingest_data(self, data_point: DataPoint) -> None:
        """Add a data point to the analysis buffer."""
        self._data_buffer.append(data_point)

    def ingest_batch(self, data_points: list[DataPoint]) -> int:
        """Add multiple data points; returns count added."""
        for dp in data_points:
            self._data_buffer.append(dp)
        return len(data_points)

    def get_buffer_stats(self) -> dict:
        """Return basic statistics on the current data buffer."""
        if not self._data_buffer:
            return {"count": 0}
        values = [dp.value for dp in self._data_buffer]
        return {
            "count": len(values),
            "mean": round(statistics.mean(values), 4),
            "min": round(min(values), 4),
            "max": round(max(values), 4),
            "stdev": round(statistics.stdev(values), 4) if len(values) > 1 else 0.0,
        }

    def clear_buffer(self) -> None:
        """Clear the data buffer."""
        self._data_buffer.clear()

    # ------------------------------------------------------------------
    # Strategy generation
    # ------------------------------------------------------------------

    def generate_strategy(
        self,
        name: str,
        strategy_type: StrategyType,
        risk_level: RiskLevel = RiskLevel.MEDIUM,
        custom_rules: Optional[list] = None,
        custom_params: Optional[dict] = None,
        client_id: Optional[str] = None,
        bot_id: Optional[str] = None,
    ) -> Strategy:
        """Generate a new Open Claw strategy."""
        self._counter += 1
        strategy_id = f"strat_{self._counter:04d}"

        # Base rules from template + any custom overrides
        rules = list(STRATEGY_RULE_TEMPLATES.get(strategy_type, []))
        if custom_rules:
            rules = custom_rules + rules

        # ROI and confidence derived from risk level and data
        risk_p = RISK_PARAMS[risk_level]
        buffer_stats = self.get_buffer_stats()
        base_confidence = 0.70 + risk_p["confidence_boost"]

        if buffer_stats["count"] > 0:
            # Slightly increase confidence when we have more data
            data_factor = min(buffer_stats["count"] / 100, 0.15)
            base_confidence = min(base_confidence + data_factor, 0.99)

        # Estimate ROI from risk band
        roi_range = risk_p["roi_max"] - risk_p["roi_base"]
        estimated_roi = round(risk_p["roi_base"] + roi_range * base_confidence, 2)

        strategy = Strategy(
            strategy_id=strategy_id,
            name=name,
            strategy_type=strategy_type,
            description=f"Open Claw {strategy_type.value} strategy with {risk_level.value} risk.",
            risk_level=risk_level,
            expected_roi_pct=estimated_roi,
            confidence_score=round(base_confidence, 4),
            rules=rules,
            custom_params=dict(custom_params or {}),
            client_id=client_id,
            bot_id=bot_id,
        )
        self._strategies[strategy_id] = strategy
        return strategy

    def rank_strategies(
        self,
        client_id: Optional[str] = None,
        bot_id: Optional[str] = None,
    ) -> list[Strategy]:
        """
        Return strategies sorted by (confidence × expected_roi) descending.
        Optionally filter by client or bot.
        """
        strategies = list(self._strategies.values())
        if client_id is not None:
            strategies = [s for s in strategies if s.client_id == client_id]
        if bot_id is not None:
            strategies = [s for s in strategies if s.bot_id == bot_id]
        return sorted(
            strategies,
            key=lambda s: s.confidence_score * s.expected_roi_pct,
            reverse=True,
        )

    # ------------------------------------------------------------------
    # Strategy lifecycle
    # ------------------------------------------------------------------

    def activate_strategy(self, strategy_id: str) -> Strategy:
        strat = self._get(strategy_id)
        strat.status = StrategyStatus.ACTIVE
        return strat

    def pause_strategy(self, strategy_id: str) -> Strategy:
        strat = self._get(strategy_id)
        strat.status = StrategyStatus.PAUSED
        return strat

    def complete_strategy(self, strategy_id: str, actual_roi_pct: float) -> Strategy:
        strat = self._get(strategy_id)
        strat.status = StrategyStatus.COMPLETED
        strat.performance_history.append(
            {"status": "completed", "actual_roi_pct": actual_roi_pct}
        )
        return strat

    def archive_strategy(self, strategy_id: str) -> Strategy:
        strat = self._get(strategy_id)
        strat.status = StrategyStatus.ARCHIVED
        return strat

    def get_strategy(self, strategy_id: str) -> Strategy:
        return self._get(strategy_id)

    def list_strategies(
        self, status: Optional[StrategyStatus] = None
    ) -> list[Strategy]:
        strategies = list(self._strategies.values())
        if status is not None:
            strategies = [s for s in strategies if s.status == status]
        return strategies

    # ------------------------------------------------------------------
    # Scenario simulation
    # ------------------------------------------------------------------

    def simulate_scenario(
        self,
        strategy_id: str,
        market_conditions: dict,
    ) -> dict:
        """
        Run a quick Monte-Carlo-style scenario simulation for a strategy.

        Parameters
        ----------
        strategy_id : str
            ID of the strategy to simulate.
        market_conditions : dict
            Key parameters like volatility, trend, volume.

        Returns
        -------
        dict
            Simulated P&L range, win rate, and max drawdown.
        """
        strat = self._get(strategy_id)
        volatility = float(market_conditions.get("volatility", 0.2))
        trend = float(market_conditions.get("trend", 0.0))
        volume = float(market_conditions.get("volume", 1.0))

        # Simplified simulation heuristic
        adjusted_roi = strat.expected_roi_pct * (1 + trend * 0.5) * volume
        adjusted_roi = round(adjusted_roi, 2)
        win_rate = round(strat.confidence_score * (1 - volatility * 0.3), 4)
        max_drawdown = round(volatility * strat.expected_roi_pct * 0.4, 2)

        return {
            "strategy_id": strategy_id,
            "simulated_roi_pct": adjusted_roi,
            "win_rate": win_rate,
            "max_drawdown_pct": max_drawdown,
            "market_conditions": market_conditions,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get(self, strategy_id: str) -> Strategy:
        if strategy_id not in self._strategies:
            raise KeyError(f"Strategy '{strategy_id}' not found.")
        return self._strategies[strategy_id]
