"""Marketplace pricing tiers for the DreamCobots platform."""


STARTER = {
    "name": "Starter",
    "price_monthly": 49,
    "price_annual": 490,
    "description": "Perfect for individuals and solopreneurs starting their AI journey.",
    "features": [
        "Access to 3 bots of your choice",
        "50% revenue share on generated income",
        "Basic compliance checklist",
        "Email support",
        "Dashboard access",
    ],
    "bot_limit": 3,
    "support_level": "email",
}

PROFESSIONAL = {
    "name": "Professional",
    "price_monthly": 149,
    "price_annual": 1490,
    "description": "Ideal for small businesses and growing entrepreneurs.",
    "features": [
        "Access to 8 bots of your choice",
        "50% revenue share on generated income",
        "Full compliance suite",
        "Priority email + chat support",
        "Custom bot configuration",
        "API access",
        "Revenue analytics dashboard",
    ],
    "bot_limit": 8,
    "support_level": "priority",
}

ENTERPRISE = {
    "name": "Enterprise",
    "price_monthly": 499,
    "price_annual": 4990,
    "description": "Full platform access for businesses with complex needs.",
    "features": [
        "Unlimited bot access",
        "50% revenue share on generated income",
        "Full compliance suite for all industries",
        "Dedicated account manager",
        "Custom integrations and webhooks",
        "White-label options",
        "SLA: 99.9% uptime guarantee",
        "Phone, chat, and email support",
        "Advanced analytics and reporting",
    ],
    "bot_limit": -1,  # Unlimited
    "support_level": "dedicated",
}

MASTER = {
    "name": "Master",
    "price_monthly": 999,
    "price_annual": 9990,
    "description": "White-label and reseller access for agencies and enterprise partners.",
    "features": [
        "Everything in Enterprise",
        "White-label dashboard with your branding",
        "Reseller program: earn on client subscriptions",
        "Custom AI model fine-tuning",
        "Dedicated infrastructure",
        "Executive-level support",
        "Quarterly strategy sessions",
        "Custom contract terms",
    ],
    "bot_limit": -1,
    "support_level": "executive",
}

ALL_TIERS = [STARTER, PROFESSIONAL, ENTERPRISE, MASTER]

REVENUE_SHARE = {
    "percentage": 50,
    "description": "DreamCobots shares 50% of all revenue generated by the platform with clients.",
    "payment_schedule": "Monthly, on the 1st of each month",
    "minimum_payout": "$50.00",
    "payment_methods": ["ACH bank transfer", "PayPal", "Cryptocurrency (BTC/ETH/USDC)"],
}
