"""DreamCo Buddy OS package."""

from bots.buddy_os.buddy_os import BuddyOS, BuddyOSError, BuddyOSTierError
from bots.buddy_os.tiers import Tier, TierConfig, get_tier_config, get_upgrade_path, list_tiers
from bots.buddy_os.device_manager import (
    DeviceManager,
    Device,
    DeviceType,
    DevicePlatform,
    DeviceStatus,
)
from bots.buddy_os.bluetooth_engine import (
    BluetoothEngine,
    BluetoothDevice,
    BluetoothProfileType,
    BluetoothState,
    FileTransfer,
)
from bots.buddy_os.cast_engine import (
    CastEngine,
    CastReceiver,
    CastSession,
    CastProtocol,
    CastState,
    ContentType,
)
from bots.buddy_os.app_framework import (
    AppRegistry,
    BrowserToolkit,
    SmartDeviceHub,
    NvidiaToolsHub,
    StarlinkManager,
    AppCategory,
    AppPlatform,
    SmartDeviceProtocol,
)
from bots.buddy_os.wifi_engine import (
    WiFiEngine,
    WiFiNetwork,
    WiFiConnection,
    WiFiHotspot,
    WiFiSecurity,
    WiFiBand,
    WiFiConnectionState,
    IoTWiFiDevice,
)
from bots.buddy_os.hardware_protocols import (
    HardwareProtocolsHub,
    UARTManager,
    I2CManager,
    SPIManager,
    OBD2Manager,
    ProtocolType,
    ChannelState,
    UARTParity,
    SPIMode,
)
from bots.buddy_os.security_manager import (
    SecurityManager,
    SyncMode,
    DeviceToken,
    EncryptionKey,
    PairingSession,
    AuditEvent,
    AuthStatus,
    EncryptionAlgorithm,
)
from bots.buddy_os.deployment_manager import (
    DeploymentManager,
    BotPackage,
    BootConfig,
    InstallRecord,
    PackageFormat,
    PackageStatus,
    InstallMethod,
)

__all__ = [
    "BuddyOS",
    "BuddyOSError",
    "BuddyOSTierError",
    "Tier",
    "TierConfig",
    "get_tier_config",
    "get_upgrade_path",
    "list_tiers",
    "DeviceManager",
    "Device",
    "DeviceType",
    "DevicePlatform",
    "DeviceStatus",
    "BluetoothEngine",
    "BluetoothDevice",
    "BluetoothProfileType",
    "BluetoothState",
    "FileTransfer",
    "CastEngine",
    "CastReceiver",
    "CastSession",
    "CastProtocol",
    "CastState",
    "ContentType",
    "AppRegistry",
    "BrowserToolkit",
    "SmartDeviceHub",
    "NvidiaToolsHub",
    "StarlinkManager",
    "AppCategory",
    "AppPlatform",
    "SmartDeviceProtocol",
    "WiFiEngine",
    "WiFiNetwork",
    "WiFiConnection",
    "WiFiHotspot",
    "WiFiSecurity",
    "WiFiBand",
    "WiFiConnectionState",
    "IoTWiFiDevice",
    "HardwareProtocolsHub",
    "UARTManager",
    "I2CManager",
    "SPIManager",
    "OBD2Manager",
    "ProtocolType",
    "ChannelState",
    "UARTParity",
    "SPIMode",
    "SecurityManager",
    "SyncMode",
    "DeviceToken",
    "EncryptionKey",
    "PairingSession",
    "AuditEvent",
    "AuthStatus",
    "EncryptionAlgorithm",
    "DeploymentManager",
    "BotPackage",
    "BootConfig",
    "InstallRecord",
    "PackageFormat",
    "PackageStatus",
    "InstallMethod",
]
