/**
 * DreamCo Control Tower — Bot Manager
 *
 * Handles GitHub-integrated bot operations:
 *   - Pull latest code from origin/main
 *   - Auto-merge conflicts
 *   - Create pull requests via the GitHub API
 *   - Heartbeat tracking
 */

import { execSync } from "child_process";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Load bot registry
// ---------------------------------------------------------------------------

function loadBots() {
  try {
    const raw = readFileSync(join(__dirname, "../config/bots.json"), "utf-8");
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// Git operations
// ---------------------------------------------------------------------------

/**
 * Pull latest changes from origin/main with automatic conflict resolution.
 * @param {string} repoPath - Local path to the git repository.
 * @returns {{ success: boolean, output: string, error?: string }}
 */
export function pullLatest(repoPath) {
  try {
    const output = execSync(`git -C "${repoPath}" pull --rebase origin main`, {
      encoding: "utf-8",
      stdio: "pipe",
    });
    return { success: true, output: output.trim() };
  } catch (err) {
    const output = err.stdout?.trim() || err.message;
    console.warn(`⚠️  Conflict in ${repoPath} — auto-resolving with --theirs`);
    try {
      const mergeOut = execSync(
        `git -C "${repoPath}" merge -X theirs origin/main`,
        { encoding: "utf-8", stdio: "pipe" }
      );
      return { success: true, output: mergeOut.trim(), autoMerged: true };
    } catch (mergeErr) {
      return {
        success: false,
        output,
        error: mergeErr.message,
        autoMerged: false,
      };
    }
  }
}

// ---------------------------------------------------------------------------
// GitHub API — Pull Requests
// ---------------------------------------------------------------------------

/**
 * Create an auto-upgrade pull request using the GitHub REST API.
 * Requires GITHUB_TOKEN to be set in the environment.
 *
 * @param {{ repo: string, head: string, title: string, body?: string }} opts
 * @returns {Promise<{ success: boolean, prUrl?: string, error?: string }>}
 */
export async function createPullRequest({ repo, head, title, body }) {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER || "ireanjordan24";

  if (!token) {
    return { success: false, error: "GITHUB_TOKEN not set in environment." };
  }

  try {
    const { Octokit } = await import("@octokit/rest");
    const octokit = new Octokit({ auth: token });

    const response = await octokit.pulls.create({
      owner,
      repo,
      title,
      body: body || "🤖 Auto-generated by DreamCo Control Tower",
      head,
      base: "main",
    });

    console.log(`✅ PR created: ${response.data.html_url}`);
    return { success: true, prUrl: response.data.html_url, prNumber: response.data.number };
  } catch (err) {
    console.error(`❌ PR creation failed for ${repo}:`, err.message);
    return { success: false, error: err.message };
  }
}

// ---------------------------------------------------------------------------
// Heartbeat
// ---------------------------------------------------------------------------

const _heartbeats = new Map();
const HEARTBEAT_TIMEOUT_MS = 60_000;

/**
 * Record a heartbeat for *botName*.
 * @param {string} botName
 */
export function ping(botName) {
  _heartbeats.set(botName, Date.now());
}

/**
 * Return live/offline status for a bot.
 * @param {string} botName
 * @returns {{ status: "live"|"offline", lastPing: number|null, msSincePing: number|null }}
 */
export function getHeartbeat(botName) {
  const last = _heartbeats.get(botName);
  if (!last) return { status: "offline", lastPing: null, msSincePing: null };
  const ms = Date.now() - last;
  return { status: ms <= HEARTBEAT_TIMEOUT_MS ? "live" : "offline", lastPing: last, msSincePing: ms };
}

/**
 * Return heartbeat status for every tracked bot.
 * @returns {Record<string, ReturnType<getHeartbeat>>}
 */
export function getAllHeartbeats() {
  const result = {};
  for (const [name] of _heartbeats) {
    result[name] = getHeartbeat(name);
  }
  return result;
}

// ---------------------------------------------------------------------------
// Bot status
// ---------------------------------------------------------------------------

/**
 * Return the full status of all configured bots.
 * @returns {Promise<Array<object>>}
 */
export async function getBotStatuses() {
  const bots = loadBots();
  return bots.map((bot) => ({
    ...bot,
    heartbeat: getHeartbeat(bot.name),
  }));
}

// ---------------------------------------------------------------------------
// Default export — convenience object
// ---------------------------------------------------------------------------

export default {
  loadBots,
  pullLatest,
  createPullRequest,
  ping,
  getHeartbeat,
  getAllHeartbeats,
  getBotStatuses,
};
