"""
Bot Generator Bot — Deployer Module

Writes the generated bot source code to the filesystem under the
``bots/`` directory and registers it for use within the Dreamcobots
ecosystem.  Supports dry-run mode (returns plan without writing files).
"""

from __future__ import annotations

import os
import sys
import json
from datetime import datetime, timezone
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from framework import GlobalAISourcesFlow  # noqa: F401  (GLOBAL AI SOURCES FLOW)


class BotDeployer:
    """
    Writes generated bot artifacts to disk.

    Usage::

        deployer = BotDeployer(bots_root="/path/to/bots")
        result = deployer.deploy(build_result)
        print(result["deployed_path"])
    """

    def __init__(self, bots_root: Optional[str] = None) -> None:
        if bots_root is None:
            bots_root = os.path.join(
                os.path.dirname(__file__), "..", ".."
            ) + "/bots"
        self.bots_root = os.path.abspath(bots_root)
        self._deploy_log: list = []

    # ------------------------------------------------------------------
    # Deploy
    # ------------------------------------------------------------------

    def deploy(self, build_result: dict, dry_run: bool = False) -> dict:
        """
        Deploy a generated bot to the filesystem.

        Parameters
        ----------
        build_result : dict
            Output from :meth:`TemplateEngine.build`.
        dry_run : bool
            When ``True``, return the deployment plan without writing files.

        Returns
        -------
        dict
            Deployment result with ``"deployed_path"``, ``"files_written"``,
            and ``"dry_run"`` keys.
        """
        bot_name: str = build_result["bot_name"]
        source: str = build_result["source"]
        dna: dict = build_result.get("dna", {})

        bot_dir = os.path.join(self.bots_root, bot_name)
        bot_file = os.path.join(bot_dir, f"{bot_name}.py")
        init_file = os.path.join(bot_dir, "__init__.py")
        config_file = os.path.join(bot_dir, "bot_config.json")
        readme_file = os.path.join(bot_dir, "README.md")

        config = {
            "bot_name": bot_name,
            "class_name": build_result.get("class_name", ""),
            "industry": dna.get("industry", "general"),
            "goal": dna.get("goal", "generate_leads"),
            "tools": dna.get("tools", []),
            "monetization": dna.get("monetization", []),
            "generated_at": build_result.get("generated_at", datetime.now(timezone.utc).isoformat()),
            "deployed_at": datetime.now(timezone.utc).isoformat(),
            "dry_run": dry_run,
        }

        readme = self._render_readme(config)

        files_to_write = {
            bot_file: source,
            init_file: f'"""Auto-generated {bot_name} package."""\n',
            config_file: json.dumps(config, indent=2),
            readme_file: readme,
        }

        if not dry_run:
            os.makedirs(bot_dir, exist_ok=True)
            for path, content in files_to_write.items():
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(content)

        log_entry = {
            "bot_name": bot_name,
            "deployed_path": bot_dir,
            "files_written": list(files_to_write.keys()),
            "dry_run": dry_run,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self._deploy_log.append(log_entry)

        return log_entry

    # ------------------------------------------------------------------
    # Deployment log
    # ------------------------------------------------------------------

    def get_deploy_log(self) -> list:
        """Return the full deployment history."""
        return list(self._deploy_log)

    def list_deployed_bots(self) -> list:
        """Return names of all deployed bots found in bots_root."""
        if not os.path.isdir(self.bots_root):
            return []
        return [
            d for d in os.listdir(self.bots_root)
            if os.path.isdir(os.path.join(self.bots_root, d))
        ]

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _render_readme(self, config: dict) -> str:
        lines = [
            f"# {config['bot_name']}",
            "",
            f"**Industry:** {config['industry']}  ",
            f"**Goal:** {config['goal']}  ",
            f"**Tools:** {', '.join(config['tools']) or 'none'}  ",
            f"**Monetization:** {', '.join(config['monetization']) or 'none'}  ",
            "",
            f"*Auto-generated by DreamCo Bot Generator on {config['generated_at'][:10]}.*",
            "",
            "## Usage",
            "",
            "```python",
            f"from bots.{config['bot_name']}.{config['bot_name']} import {config['class_name']}",
            "",
            f"bot = {config['class_name']}()",
            "result = bot.run(count=20)",
            "print(result['summary'])",
            "```",
            "",
            "## Configuration",
            "",
            "Set the following environment variables before running:",
            "",
        ]
        return "\n".join(lines)
