"""
DreamCo Bot Generator — Generator

Provides a high-level interface for dynamically creating new bot directories,
writing functional bot file templates, and registering the newly-created bots
with the Controller / ControlCenter.

GLOBAL AI SOURCES FLOW compliant.
"""

from __future__ import annotations

import importlib
import logging
import os
import re
import sys
import textwrap
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Optional

from framework import GlobalAISourcesFlow  # noqa: F401  (GLOBAL AI SOURCES FLOW)

if TYPE_CHECKING:
    from bots.control_center.controller import Controller

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Default bot template
# ---------------------------------------------------------------------------

_BOT_TEMPLATE = '''\
"""
{bot_name} — Auto-generated by DreamCo Bot Generator
Generated at: {generated_at}

GLOBAL AI SOURCES FLOW compliant.
"""

from __future__ import annotations

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from framework import GlobalAISourcesFlow  # noqa: F401  (GLOBAL AI SOURCES FLOW)


class {class_name}:
    """Auto-generated DreamCo bot: {bot_name}."""

    def __init__(self) -> None:
        self.name = "{bot_name}"
        self._run_count: int = 0

    def run(self) -> str:
        """Execute the bot's primary task."""
        self._run_count += 1
        return f"{{self.name}} — run #{{self._run_count}} complete."

    def get_status(self) -> dict:
        """Return current bot status."""
        return {{
            "name": self.name,
            "run_count": self._run_count,
            "status": "idle",
        }}

    def process(self, payload: dict) -> dict:
        """GLOBAL AI SOURCES FLOW framework entry point."""
        command = payload.get("command", "run")
        if command == "run":
            return {{"status": "ok", "result": self.run()}}
        if command == "status":
            return {{"status": "ok", "result": self.get_status()}}
        return {{"status": "unknown_command", "command": command}}
'''

_INIT_TEMPLATE = '''\
"""{bot_name} package."""
from .{module_name} import {class_name}

__all__ = ["{class_name}"]
'''

_README_TEMPLATE = """\
# {bot_name}

Auto-generated DreamCo bot.

## Usage

```python
from bots.{module_name}.{module_name} import {class_name}

bot = {class_name}()
print(bot.run())
```
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _to_snake_case(name: str) -> str:
    """Convert a human-readable name to snake_case module name."""
    name = re.sub(r"[^\w\s]", "", name)
    name = re.sub(r"\s+", "_", name.strip())
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", name)
    return name.lower()


def _to_class_name(name: str) -> str:
    """Convert a human-readable name to PascalCase class name."""
    parts = re.split(r"[\s_\-]+", re.sub(r"[^\w\s\-]", "", name))
    return "".join(p.capitalize() for p in parts if p)


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class Generator:
    """
    DreamCo Bot Generator — the self-build engine.

    Creates new bot directories on disk, writes functional bot files from a
    standard template, and optionally registers the new bot with a
    :class:`~bots.control_center.controller.Controller` instance.

    Parameters
    ----------
    bots_root : str, optional
        Filesystem path to the ``bots/`` directory.  Defaults to the sibling
        ``bots/`` directory relative to this file.
    controller : Controller, optional
        If provided, newly-generated bots are automatically registered.
    """

    def __init__(
        self,
        bots_root: str | None = None,
        controller: "Controller | None" = None,
    ) -> None:
        if bots_root is None:
            bots_root = os.path.join(os.path.dirname(__file__), "..")
        self.bots_root = os.path.abspath(bots_root)
        self._controller = controller
        self._generation_log: list = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def create_bot(
        self,
        bot_name: str,
        *,
        template: str | None = None,
        dry_run: bool = False,
        register: bool = True,
    ) -> dict:
        """
        Create a new bot directory and write functional source files.

        Parameters
        ----------
        bot_name : str
            Human-readable bot name, e.g. ``"Dentist Lead Bot"``.
        template : str, optional
            Custom source-code template string.  Uses the built-in template
            when omitted.
        dry_run : bool
            When ``True`` returns the planned file paths without writing.
        register : bool
            When ``True`` (and a controller was supplied), register the new
            bot with the Controller after creation.

        Returns
        -------
        dict
            Result containing ``bot_name``, ``module_name``, ``class_name``,
            ``bot_dir``, ``files``, ``dry_run``, and ``registered``.
        """
        module_name = _to_snake_case(bot_name)
        class_name = _to_class_name(bot_name)
        bot_dir = os.path.join(self.bots_root, module_name)
        generated_at = datetime.now(timezone.utc).isoformat()

        source_tpl = template if template is not None else _BOT_TEMPLATE
        source = source_tpl.format(
            bot_name=bot_name,
            module_name=module_name,
            class_name=class_name,
            generated_at=generated_at,
        )

        init_content = _INIT_TEMPLATE.format(
            bot_name=bot_name,
            module_name=module_name,
            class_name=class_name,
        )
        readme_content = _README_TEMPLATE.format(
            bot_name=bot_name,
            module_name=module_name,
            class_name=class_name,
        )

        files = {
            os.path.join(bot_dir, f"{module_name}.py"): source,
            os.path.join(bot_dir, "__init__.py"): init_content,
            os.path.join(bot_dir, "README.md"): readme_content,
        }

        result: dict = {
            "bot_name": bot_name,
            "module_name": module_name,
            "class_name": class_name,
            "bot_dir": bot_dir,
            "files": list(files.keys()),
            "dry_run": dry_run,
            "registered": False,
            "generated_at": generated_at,
        }

        if not dry_run:
            os.makedirs(bot_dir, exist_ok=True)
            for file_path, content in files.items():
                with open(file_path, "w", encoding="utf-8") as fh:
                    fh.write(content)
            logger.info("Created bot '%s' at %s", bot_name, bot_dir)

            if register and self._controller is not None:
                registered = self._register_with_controller(
                    module_name, class_name, bot_dir
                )
                result["registered"] = registered

        self._generation_log.append(result)
        return result

    def create_bots_bulk(self, bot_names: list[str], **kwargs) -> list[dict]:
        """Create multiple bots in one call."""
        return [self.create_bot(name, **kwargs) for name in bot_names]

    def get_generation_log(self) -> list:
        """Return a copy of all generation records for this session."""
        return list(self._generation_log)

    def get_summary(self) -> dict:
        """Return a summary of generator activity."""
        return {
            "bots_root": self.bots_root,
            "total_bots_generated": len(self._generation_log),
            "bots": [
                {
                    "bot_name": r["bot_name"],
                    "module_name": r["module_name"],
                    "registered": r["registered"],
                }
                for r in self._generation_log
            ],
        }

    def set_controller(self, controller: "Controller") -> None:
        """Attach (or replace) the controller used for auto-registration."""
        self._controller = controller

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _register_with_controller(
        self, module_name: str, class_name: str, bot_dir: str
    ) -> bool:
        """Attempt to import the newly-created bot and register it."""
        repo_root = os.path.abspath(os.path.join(self.bots_root, ".."))
        if repo_root not in sys.path:
            sys.path.insert(0, repo_root)
        try:
            # Reload so the newly-written file is picked up.
            full_module = f"bots.{module_name}.{module_name}"
            if full_module in sys.modules:
                mod = importlib.reload(sys.modules[full_module])
            else:
                mod = importlib.import_module(full_module)
            cls = getattr(mod, class_name)
            instance = cls()
            self._controller.register_bot(module_name, instance)  # type: ignore[union-attr]
            logger.info("Registered new bot '%s' with controller", module_name)
            return True
        except Exception as exc:
            logger.warning("Could not register bot '%s': %s", module_name, exc)
            return False
