"""API Registry for DataForge AI - maps all 100 APIs to metadata."""
# Adheres to the GLOBAL AI SOURCES FLOW framework — see framework/global_ai_sources_flow.py

API_REGISTRY = {
    "openai": {
        "class": "OpenAIConnector",
        "module": "bots.dataforge.apis.connectors.openai_connector",
        "category": "AI & Machine Learning",
        "description": "OpenAI GPT models",
        "free_tier": True,
    },
    "huggingface": {
        "class": "HuggingFaceConnector",
        "module": "bots.dataforge.apis.connectors.huggingface_connector",
        "category": "AI & Machine Learning",
        "description": "HuggingFace Inference API",
        "free_tier": True,
    },
    "google_gemini": {
        "class": "GoogleGeminiConnector",
        "module": "bots.dataforge.apis.connectors.google_gemini_connector",
        "category": "AI & Machine Learning",
        "description": "Google Gemini generative AI",
        "free_tier": True,
    },
    "cohere": {
        "class": "CohereConnector",
        "module": "bots.dataforge.apis.connectors.cohere_connector",
        "category": "AI & Machine Learning",
        "description": "Cohere NLP generation and embedding",
        "free_tier": True,
    },
    "mistral": {
        "class": "MistralConnector",
        "module": "bots.dataforge.apis.connectors.mistral_connector",
        "category": "AI & Machine Learning",
        "description": "Mistral AI chat models",
        "free_tier": True,
    },
    "together_ai": {
        "class": "TogetherAIConnector",
        "module": "bots.dataforge.apis.connectors.together_ai_connector",
        "category": "AI & Machine Learning",
        "description": "Together AI open source model hosting",
        "free_tier": True,
    },
    "replicate": {
        "class": "ReplicateConnector",
        "module": "bots.dataforge.apis.connectors.replicate_connector",
        "category": "AI & Machine Learning",
        "description": "Replicate ML model deployment",
        "free_tier": False,
    },
    "deepai": {
        "class": "DeepAIConnector",
        "module": "bots.dataforge.apis.connectors.deepai_connector",
        "category": "AI & Machine Learning",
        "description": "DeepAI text and image APIs",
        "free_tier": True,
    },
    "stability_ai": {
        "class": "StabilityAIConnector",
        "module": "bots.dataforge.apis.connectors.stability_ai_connector",
        "category": "AI & Machine Learning",
        "description": "Stability AI image generation",
        "free_tier": False,
    },
    "clarifai": {
        "class": "ClarifaiConnector",
        "module": "bots.dataforge.apis.connectors.clarifai_connector",
        "category": "AI & Machine Learning",
        "description": "Clarifai visual AI platform",
        "free_tier": True,
    },
    "eden_ai": {
        "class": "EdenAIConnector",
        "module": "bots.dataforge.apis.connectors.eden_ai_connector",
        "category": "AI & Machine Learning",
        "description": "Eden AI multi-provider hub",
        "free_tier": True,
    },
    "nlp_cloud": {
        "class": "NLPCloudConnector",
        "module": "bots.dataforge.apis.connectors.nlp_cloud_connector",
        "category": "AI & Machine Learning",
        "description": "NLP Cloud hosted NLP models",
        "free_tier": True,
    },
    "monkeylearn": {
        "class": "MonkeyLearnConnector",
        "module": "bots.dataforge.apis.connectors.monkeylearn_connector",
        "category": "AI & Machine Learning",
        "description": "MonkeyLearn text analysis",
        "free_tier": True,
    },
    "wit_ai": {
        "class": "WitAIConnector",
        "module": "bots.dataforge.apis.connectors.wit_ai_connector",
        "category": "AI & Machine Learning",
        "description": "Wit.ai natural language understanding",
        "free_tier": True,
    },
    "dialogflow": {
        "class": "DialogflowConnector",
        "module": "bots.dataforge.apis.connectors.dialogflow_connector",
        "category": "AI & Machine Learning",
        "description": "Google Dialogflow conversational AI",
        "free_tier": True,
    },
    "mozilla_common_voice": {
        "class": "MozillaCommonVoiceConnector",
        "module": "bots.dataforge.apis.connectors.mozilla_common_voice_connector",
        "category": "Speech & Voice",
        "description": "Mozilla Common Voice open dataset",
        "free_tier": True,
    },
    "assemblyai": {
        "class": "AssemblyAIConnector",
        "module": "bots.dataforge.apis.connectors.assemblyai_connector",
        "category": "Speech & Voice",
        "description": "AssemblyAI speech transcription",
        "free_tier": True,
    },
    "speechly": {
        "class": "SpeechlyConnector",
        "module": "bots.dataforge.apis.connectors.speechly_connector",
        "category": "Speech & Voice",
        "description": "Speechly real-time speech recognition",
        "free_tier": True,
    },
    "deepgram": {
        "class": "DeepgramConnector",
        "module": "bots.dataforge.apis.connectors.deepgram_connector",
        "category": "Speech & Voice",
        "description": "Deepgram speech-to-text API",
        "free_tier": True,
    },
    "rev_ai": {
        "class": "RevAIConnector",
        "module": "bots.dataforge.apis.connectors.rev_ai_connector",
        "category": "Speech & Voice",
        "description": "Rev.ai high-accuracy transcription",
        "free_tier": True,
    },
    "vosk": {
        "class": "VoskConnector",
        "module": "bots.dataforge.apis.connectors.vosk_connector",
        "category": "Speech & Voice",
        "description": "Vosk offline speech recognition",
        "free_tier": True,
    },
    "picovoice": {
        "class": "PicovoiceConnector",
        "module": "bots.dataforge.apis.connectors.picovoice_connector",
        "category": "Speech & Voice",
        "description": "Picovoice wake word detection",
        "free_tier": False,
    },
    "speechbrain": {
        "class": "SpeechBrainConnector",
        "module": "bots.dataforge.apis.connectors.speechbrain_connector",
        "category": "Speech & Voice",
        "description": "SpeechBrain deep learning toolkit",
        "free_tier": True,
    },
    "whisper": {
        "class": "WhisperConnector",
        "module": "bots.dataforge.apis.connectors.whisper_connector",
        "category": "Speech & Voice",
        "description": "OpenAI Whisper ASR",
        "free_tier": True,
    },
    "elevenlabs": {
        "class": "ElevenLabsConnector",
        "module": "bots.dataforge.apis.connectors.elevenlabs_connector",
        "category": "Speech & Voice",
        "description": "ElevenLabs text-to-speech",
        "free_tier": True,
    },
    "facepp": {
        "class": "FacePPConnector",
        "module": "bots.dataforge.apis.connectors.facepp_connector",
        "category": "Computer Vision",
        "description": "Face++ facial recognition",
        "free_tier": True,
    },
    "aws_rekognition": {
        "class": "AWSRekognitionConnector",
        "module": "bots.dataforge.apis.connectors.aws_rekognition_connector",
        "category": "Computer Vision",
        "description": "AWS Rekognition image analysis",
        "free_tier": True,
    },
    "google_vision": {
        "class": "GoogleVisionConnector",
        "module": "bots.dataforge.apis.connectors.google_vision_connector",
        "category": "Computer Vision",
        "description": "Google Cloud Vision API",
        "free_tier": True,
    },
    "azure_face": {
        "class": "AzureFaceConnector",
        "module": "bots.dataforge.apis.connectors.azure_face_connector",
        "category": "Computer Vision",
        "description": "Azure Face API detection",
        "free_tier": True,
    },
    "deepface": {
        "class": "DeepFaceConnector",
        "module": "bots.dataforge.apis.connectors.deepface_connector",
        "category": "Computer Vision",
        "description": "DeepFace facial analysis library",
        "free_tier": True,
    },
    "opencv": {
        "class": "OpenCVConnector",
        "module": "bots.dataforge.apis.connectors.opencv_connector",
        "category": "Computer Vision",
        "description": "OpenCV computer vision library",
        "free_tier": True,
    },
    "roboflow": {
        "class": "RoboflowConnector",
        "module": "bots.dataforge.apis.connectors.roboflow_connector",
        "category": "Computer Vision",
        "description": "Roboflow model inference",
        "free_tier": True,
    },
    "imagga": {
        "class": "ImaggaConnector",
        "module": "bots.dataforge.apis.connectors.imagga_connector",
        "category": "Computer Vision",
        "description": "Imagga image tagging and categorization",
        "free_tier": True,
    },
    "clarifai_vision": {
        "class": "ClarifaiVisionConnector",
        "module": "bots.dataforge.apis.connectors.clarifai_vision_connector",
        "category": "Computer Vision",
        "description": "Clarifai general object detection",
        "free_tier": True,
    },
    "tensorflow_vision": {
        "class": "TensorFlowVisionConnector",
        "module": "bots.dataforge.apis.connectors.tensorflow_vision_connector",
        "category": "Computer Vision",
        "description": "TensorFlow image classification",
        "free_tier": True,
    },
    "kaggle": {
        "class": "KaggleConnector",
        "module": "bots.dataforge.apis.connectors.kaggle_connector",
        "category": "Datasets & Research",
        "description": "Kaggle dataset search and download",
        "free_tier": True,
    },
    "huggingface_datasets": {
        "class": "HuggingFaceDatasetsConnector",
        "module": "bots.dataforge.apis.connectors.huggingface_datasets_connector",
        "category": "Datasets & Research",
        "description": "HuggingFace Datasets server",
        "free_tier": True,
    },
    "nasa": {
        "class": "NASAConnector",
        "module": "bots.dataforge.apis.connectors.nasa_connector",
        "category": "Datasets & Research",
        "description": "NASA Open APIs",
        "free_tier": True,
    },
    "world_bank": {
        "class": "WorldBankConnector",
        "module": "bots.dataforge.apis.connectors.world_bank_connector",
        "category": "Datasets & Research",
        "description": "World Bank Open Data",
        "free_tier": True,
    },
    "datagov": {
        "class": "DataGovConnector",
        "module": "bots.dataforge.apis.connectors.datagov_connector",
        "category": "Datasets & Research",
        "description": "Data.gov US open data catalog",
        "free_tier": True,
    },
    "openstreetmap": {
        "class": "OpenStreetMapConnector",
        "module": "bots.dataforge.apis.connectors.openstreetmap_connector",
        "category": "Location & Maps",
        "description": "OpenStreetMap Nominatim geocoding",
        "free_tier": True,
    },
    "un_data": {
        "class": "UNDataConnector",
        "module": "bots.dataforge.apis.connectors.un_data_connector",
        "category": "Datasets & Research",
        "description": "UN Data statistics",
        "free_tier": True,
    },
    "noaa_climate": {
        "class": "NOAAClimateConnector",
        "module": "bots.dataforge.apis.connectors.noaa_climate_connector",
        "category": "Datasets & Research",
        "description": "NOAA Climate Data Online",
        "free_tier": True,
    },
    "pubmed": {
        "class": "PubMedConnector",
        "module": "bots.dataforge.apis.connectors.pubmed_connector",
        "category": "Datasets & Research",
        "description": "PubMed biomedical literature",
        "free_tier": True,
    },
    "arxiv": {
        "class": "ArXivConnector",
        "module": "bots.dataforge.apis.connectors.arxiv_connector",
        "category": "Datasets & Research",
        "description": "ArXiv preprint repository",
        "free_tier": True,
    },
    "semantic_scholar": {
        "class": "SemanticScholarConnector",
        "module": "bots.dataforge.apis.connectors.semantic_scholar_connector",
        "category": "Datasets & Research",
        "description": "Semantic Scholar academic search",
        "free_tier": True,
    },
    "crossref": {
        "class": "CrossRefConnector",
        "module": "bots.dataforge.apis.connectors.crossref_connector",
        "category": "Datasets & Research",
        "description": "CrossRef scholarly DOI metadata",
        "free_tier": True,
    },
    "core": {
        "class": "COREConnector",
        "module": "bots.dataforge.apis.connectors.core_connector",
        "category": "Datasets & Research",
        "description": "CORE open access research",
        "free_tier": True,
    },
    "openalex": {
        "class": "OpenAlexConnector",
        "module": "bots.dataforge.apis.connectors.openalex_connector",
        "category": "Datasets & Research",
        "description": "OpenAlex scholarly works graph",
        "free_tier": True,
    },
    "eurostat": {
        "class": "EurostatConnector",
        "module": "bots.dataforge.apis.connectors.eurostat_connector",
        "category": "Datasets & Research",
        "description": "Eurostat EU statistics",
        "free_tier": True,
    },
    "coingecko": {
        "class": "CoinGeckoConnector",
        "module": "bots.dataforge.apis.connectors.coingecko_connector",
        "category": "Finance & Crypto",
        "description": "CoinGecko cryptocurrency data",
        "free_tier": True,
    },
    "alpha_vantage": {
        "class": "AlphaVantageConnector",
        "module": "bots.dataforge.apis.connectors.alpha_vantage_connector",
        "category": "Finance & Crypto",
        "description": "Alpha Vantage stock and forex data",
        "free_tier": True,
    },
    "finnhub": {
        "class": "FinnhubConnector",
        "module": "bots.dataforge.apis.connectors.finnhub_connector",
        "category": "Finance & Crypto",
        "description": "Finnhub financial data",
        "free_tier": True,
    },
    "fixer": {
        "class": "FixerConnector",
        "module": "bots.dataforge.apis.connectors.fixer_connector",
        "category": "Finance & Crypto",
        "description": "Fixer.io currency exchange rates",
        "free_tier": True,
    },
    "open_exchange_rates": {
        "class": "OpenExchangeRatesConnector",
        "module": "bots.dataforge.apis.connectors.open_exchange_rates_connector",
        "category": "Finance & Crypto",
        "description": "Open Exchange Rates currency API",
        "free_tier": True,
    },
    "coincap": {
        "class": "CoinCapConnector",
        "module": "bots.dataforge.apis.connectors.coincap_connector",
        "category": "Finance & Crypto",
        "description": "CoinCap crypto market data",
        "free_tier": True,
    },
    "polygon": {
        "class": "PolygonConnector",
        "module": "bots.dataforge.apis.connectors.polygon_connector",
        "category": "Finance & Crypto",
        "description": "Polygon.io stock market data",
        "free_tier": True,
    },
    "yahoo_finance": {
        "class": "YahooFinanceConnector",
        "module": "bots.dataforge.apis.connectors.yahoo_finance_connector",
        "category": "Finance & Crypto",
        "description": "Yahoo Finance market data",
        "free_tier": True,
    },
    "quandl": {
        "class": "QuandlConnector",
        "module": "bots.dataforge.apis.connectors.quandl_connector",
        "category": "Finance & Crypto",
        "description": "Quandl/Nasdaq financial datasets",
        "free_tier": False,
    },
    "cryptocompare": {
        "class": "CryptoCompareConnector",
        "module": "bots.dataforge.apis.connectors.cryptocompare_connector",
        "category": "Finance & Crypto",
        "description": "CryptoCompare cryptocurrency data",
        "free_tier": True,
    },
    "openweathermap": {
        "class": "OpenWeatherMapConnector",
        "module": "bots.dataforge.apis.connectors.openweathermap_connector",
        "category": "Weather & Climate",
        "description": "OpenWeatherMap weather API",
        "free_tier": True,
    },
    "open_meteo": {
        "class": "OpenMeteoConnector",
        "module": "bots.dataforge.apis.connectors.open_meteo_connector",
        "category": "Weather & Climate",
        "description": "Open-Meteo free weather API",
        "free_tier": True,
    },
    "weatherapi": {
        "class": "WeatherAPIConnector",
        "module": "bots.dataforge.apis.connectors.weatherapi_connector",
        "category": "Weather & Climate",
        "description": "WeatherAPI.com weather data",
        "free_tier": True,
    },
    "visual_crossing": {
        "class": "VisualCrossingConnector",
        "module": "bots.dataforge.apis.connectors.visual_crossing_connector",
        "category": "Weather & Climate",
        "description": "Visual Crossing historical weather",
        "free_tier": True,
    },
    "storm_glass": {
        "class": "StormGlassConnector",
        "module": "bots.dataforge.apis.connectors.storm_glass_connector",
        "category": "Weather & Climate",
        "description": "Storm Glass marine weather API",
        "free_tier": False,
    },
    "airvisual": {
        "class": "AirVisualConnector",
        "module": "bots.dataforge.apis.connectors.airvisual_connector",
        "category": "Weather & Climate",
        "description": "AirVisual air quality data",
        "free_tier": True,
    },
    "climacell": {
        "class": "ClimacellConnector",
        "module": "bots.dataforge.apis.connectors.climacell_connector",
        "category": "Weather & Climate",
        "description": "Climacell/Tomorrow.io weather intelligence",
        "free_tier": True,
    },
    "newsapi": {
        "class": "NewsAPIConnector",
        "module": "bots.dataforge.apis.connectors.newsapi_connector",
        "category": "News & Media",
        "description": "NewsAPI global news aggregator",
        "free_tier": True,
    },
    "gnews": {
        "class": "GNewsConnector",
        "module": "bots.dataforge.apis.connectors.gnews_connector",
        "category": "News & Media",
        "description": "GNews global news search",
        "free_tier": True,
    },
    "currents": {
        "class": "CurrentsConnector",
        "module": "bots.dataforge.apis.connectors.currents_connector",
        "category": "News & Media",
        "description": "Currents API real-time news",
        "free_tier": True,
    },
    "guardian": {
        "class": "GuardianConnector",
        "module": "bots.dataforge.apis.connectors.guardian_connector",
        "category": "News & Media",
        "description": "The Guardian news API",
        "free_tier": True,
    },
    "nytimes": {
        "class": "NYTimesConnector",
        "module": "bots.dataforge.apis.connectors.nytimes_connector",
        "category": "News & Media",
        "description": "New York Times articles and stories",
        "free_tier": True,
    },
    "mediastack": {
        "class": "MediaStackConnector",
        "module": "bots.dataforge.apis.connectors.mediastack_connector",
        "category": "News & Media",
        "description": "MediaStack live news API",
        "free_tier": True,
    },
    "bing_news": {
        "class": "BingNewsConnector",
        "module": "bots.dataforge.apis.connectors.bing_news_connector",
        "category": "News & Media",
        "description": "Microsoft Bing News Search",
        "free_tier": False,
    },
    "open_food_facts": {
        "class": "OpenFoodFactsConnector",
        "module": "bots.dataforge.apis.connectors.open_food_facts_connector",
        "category": "E-Commerce",
        "description": "Open Food Facts nutrition data",
        "free_tier": True,
    },
    "best_buy": {
        "class": "BestBuyConnector",
        "module": "bots.dataforge.apis.connectors.best_buy_connector",
        "category": "E-Commerce",
        "description": "Best Buy product catalog API",
        "free_tier": True,
    },
    "ebay": {
        "class": "EbayConnector",
        "module": "bots.dataforge.apis.connectors.ebay_connector",
        "category": "E-Commerce",
        "description": "eBay Browse API marketplace",
        "free_tier": False,
    },
    "etsy": {
        "class": "EtsyConnector",
        "module": "bots.dataforge.apis.connectors.etsy_connector",
        "category": "E-Commerce",
        "description": "Etsy handmade marketplace API",
        "free_tier": False,
    },
    "barcode_lookup": {
        "class": "BarcodeLookupConnector",
        "module": "bots.dataforge.apis.connectors.barcode_lookup_connector",
        "category": "E-Commerce",
        "description": "Barcode Lookup product data",
        "free_tier": False,
    },
    "upc_itemdb": {
        "class": "UPCItemDBConnector",
        "module": "bots.dataforge.apis.connectors.upc_itemdb_connector",
        "category": "E-Commerce",
        "description": "UPC ItemDB product lookup",
        "free_tier": True,
    },
    "reddit": {
        "class": "RedditConnector",
        "module": "bots.dataforge.apis.connectors.reddit_connector",
        "category": "Social & Communication",
        "description": "Reddit public JSON API",
        "free_tier": True,
    },
    "twitter": {
        "class": "TwitterConnector",
        "module": "bots.dataforge.apis.connectors.twitter_connector",
        "category": "Social & Communication",
        "description": "Twitter/X API v2",
        "free_tier": False,
    },
    "discord": {
        "class": "DiscordConnector",
        "module": "bots.dataforge.apis.connectors.discord_connector",
        "category": "Social & Communication",
        "description": "Discord Bot API",
        "free_tier": False,
    },
    "telegram": {
        "class": "TelegramConnector",
        "module": "bots.dataforge.apis.connectors.telegram_connector",
        "category": "Social & Communication",
        "description": "Telegram Bot API",
        "free_tier": True,
    },
    "twilio": {
        "class": "TwilioConnector",
        "module": "bots.dataforge.apis.connectors.twilio_connector",
        "category": "Social & Communication",
        "description": "Twilio SMS and voice API",
        "free_tier": False,
    },
    "sendgrid": {
        "class": "SendGridConnector",
        "module": "bots.dataforge.apis.connectors.sendgrid_connector",
        "category": "Social & Communication",
        "description": "SendGrid transactional email",
        "free_tier": True,
    },
    "google_maps": {
        "class": "GoogleMapsConnector",
        "module": "bots.dataforge.apis.connectors.google_maps_connector",
        "category": "Location & Maps",
        "description": "Google Maps geocoding and directions",
        "free_tier": True,
    },
    "mapbox": {
        "class": "MapboxConnector",
        "module": "bots.dataforge.apis.connectors.mapbox_connector",
        "category": "Location & Maps",
        "description": "Mapbox geolocation and mapping",
        "free_tier": True,
    },
    "opencage": {
        "class": "OpenCageConnector",
        "module": "bots.dataforge.apis.connectors.opencage_connector",
        "category": "Location & Maps",
        "description": "OpenCage geocoding API",
        "free_tier": True,
    },
    "ip_api": {
        "class": "IPAPIConnector",
        "module": "bots.dataforge.apis.connectors.ip_api_connector",
        "category": "Location & Maps",
        "description": "IP-API geolocation lookup",
        "free_tier": True,
    },
    "what3words": {
        "class": "What3WordsConnector",
        "module": "bots.dataforge.apis.connectors.what3words_connector",
        "category": "Location & Maps",
        "description": "What3Words 3-word addressing",
        "free_tier": True,
    },
    "qr_code": {
        "class": "QRCodeConnector",
        "module": "bots.dataforge.apis.connectors.qr_code_connector",
        "category": "Utilities & Misc",
        "description": "QR code generation and reading",
        "free_tier": True,
    },
    "bitly": {
        "class": "BitlyConnector",
        "module": "bots.dataforge.apis.connectors.bitly_connector",
        "category": "Utilities & Misc",
        "description": "Bitly URL shortener",
        "free_tier": True,
    },
    "mailchimp": {
        "class": "MailchimpConnector",
        "module": "bots.dataforge.apis.connectors.mailchimp_connector",
        "category": "Utilities & Misc",
        "description": "Mailchimp email marketing",
        "free_tier": True,
    },
    "stripe": {
        "class": "StripeConnector",
        "module": "bots.dataforge.apis.connectors.stripe_connector",
        "category": "Utilities & Misc",
        "description": "Stripe payments processing",
        "free_tier": False,
    },
    "paypal": {
        "class": "PayPalConnector",
        "module": "bots.dataforge.apis.connectors.paypal_connector",
        "category": "Utilities & Misc",
        "description": "PayPal payments API",
        "free_tier": False,
    },
    "twitch": {
        "class": "TwitchConnector",
        "module": "bots.dataforge.apis.connectors.twitch_connector",
        "category": "Social & Communication",
        "description": "Twitch live streaming API",
        "free_tier": False,
    },
    "spotify": {
        "class": "SpotifyConnector",
        "module": "bots.dataforge.apis.connectors.spotify_connector",
        "category": "Social & Communication",
        "description": "Spotify music catalog API",
        "free_tier": False,
    },
    "youtube": {
        "class": "YouTubeConnector",
        "module": "bots.dataforge.apis.connectors.youtube_connector",
        "category": "Social & Communication",
        "description": "YouTube Data API v3",
        "free_tier": True,
    },
    "github": {
        "class": "GitHubConnector",
        "module": "bots.dataforge.apis.connectors.github_connector",
        "category": "Utilities & Misc",
        "description": "GitHub REST API",
        "free_tier": True,
    },
}
