name: DreamCo Auto Build

on:
  push:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run DreamCo
        run: python main.py
