name: DreamCo Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Force clean install
        run: rm -rf node_modules
      - run: npm install
      - run: npm run build
