name: Manage Pull Requests

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PR checks
      run: |
        npm run run-pr-checks
